// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collapse.sql

package db

import (
	"context"
)

const bumpSessionCounter = `-- name: BumpSessionCounter :exec
INSERT INTO session_counters (
    session_id,
    name,
    value
) VALUES (
    ?, ?, ?
)
ON CONFLICT (session_id, name)
DO UPDATE SET value = value + excluded.value
`

type BumpSessionCounterParams struct {
	SessionID string `json:"session_id"`
	Name      string `json:"name"`
	Value     int64  `json:"value"`
}

func (q *Queries) BumpSessionCounter(ctx context.Context, arg BumpSessionCounterParams) error {
	_, err := q.exec(ctx, q.bumpSessionCounterStmt, bumpSessionCounter, arg.SessionID, arg.Name, arg.Value)
	return err
}

const getCollapsedTurnStats = `-- name: GetCollapsedTurnStats :one
SELECT
    COUNT(*) AS turns,
    COALESCE(SUM(events), 0) AS events,
    COUNT(DISTINCT session_id) AS sessions
FROM collapsed_turns
`

type GetCollapsedTurnStatsRow struct {
	Turns    int64       `json:"turns"`
	Events   interface{} `json:"events"`
	Sessions int64       `json:"sessions"`
}

func (q *Queries) GetCollapsedTurnStats(ctx context.Context) (GetCollapsedTurnStatsRow, error) {
	row := q.queryRow(ctx, q.getCollapsedTurnStatsStmt, getCollapsedTurnStats)
	var i GetCollapsedTurnStatsRow
	err := row.Scan(&i.Turns, &i.Events, &i.Sessions)
	return i, err
}

const getSessionCounter = `-- name: GetSessionCounter :one
SELECT CAST(COALESCE(
    (SELECT value FROM session_counters WHERE session_id = ? AND name = ?),
    0
) AS INTEGER) AS value
`

type GetSessionCounterParams struct {
	SessionID string `json:"session_id"`
	Name      string `json:"name"`
}

func (q *Queries) GetSessionCounter(ctx context.Context, arg GetSessionCounterParams) (int64, error) {
	row := q.queryRow(ctx, q.getSessionCounterStmt, getSessionCounter, arg.SessionID, arg.Name)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const listSessionCounters = `-- name: ListSessionCounters :many
SELECT
    name,
    COALESCE(SUM(value), 0) AS value,
    COUNT(DISTINCT session_id) AS sessions
FROM session_counters
GROUP BY name
`

type ListSessionCountersRow struct {
	Name     string      `json:"name"`
	Value    interface{} `json:"value"`
	Sessions int64       `json:"sessions"`
}

func (q *Queries) ListSessionCounters(ctx context.Context) ([]ListSessionCountersRow, error) {
	rows, err := q.query(ctx, q.listSessionCountersStmt, listSessionCounters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionCountersRow{}
	for rows.Next() {
		var i ListSessionCountersRow
		if err := rows.Scan(&i.Name, &i.Value, &i.Sessions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCollapsedTurn = `-- name: RecordCollapsedTurn :execrows
INSERT OR IGNORE INTO collapsed_turns (
    session_id,
    turn_number,
    events,
    created_at
) VALUES (
    ?, ?, ?, strftime('%s', 'now')
)
`

type RecordCollapsedTurnParams struct {
	SessionID  string `json:"session_id"`
	TurnNumber int64  `json:"turn_number"`
	Events     int64  `json:"events"`
}

// One row per collapsed prior turn; INSERT OR IGNORE makes the write
// idempotent across renders and across processes sharing the session
// DB, so callers count a turn only when this reports a new row.
func (q *Queries) RecordCollapsedTurn(ctx context.Context, arg RecordCollapsedTurnParams) (int64, error) {
	result, err := q.exec(ctx, q.recordCollapsedTurnStmt, recordCollapsedTurn, arg.SessionID, arg.TurnNumber, arg.Events)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
