// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commands.sql

package db

import (
	"context"
)

const claimCommandPartition = `-- name: ClaimCommandPartition :exec
UPDATE command_memory SET project_key = ? WHERE project_key = ''
`

func (q *Queries) ClaimCommandPartition(ctx context.Context, projectKey string) error {
	_, err := q.exec(ctx, q.claimCommandPartitionStmt, claimCommandPartition, projectKey)
	return err
}

const deleteFailure = `-- name: DeleteFailure :exec
DELETE FROM failure_memory WHERE signature = ?
`

func (q *Queries) DeleteFailure(ctx context.Context, signature string) error {
	_, err := q.exec(ctx, q.deleteFailureStmt, deleteFailure, signature)
	return err
}

const deleteLegacyCommandConflicts = `-- name: DeleteLegacyCommandConflicts :exec
DELETE FROM command_memory WHERE project_key = '' AND EXISTS (
    SELECT 1 FROM command_memory twin
    WHERE twin.project_key = ?
        AND twin.cmd_norm = command_memory.cmd_norm
        AND twin.cwd = command_memory.cwd
)
`

// Claim collision on command_memory: project_key is PK material, so
// claiming a legacy row whose (cmd_norm, cwd, project_key) twin
// already exists conflicts. The partitioned twin wins -- fresher
// provenance -- so the stale legacy row goes before the claim update.
func (q *Queries) DeleteLegacyCommandConflicts(ctx context.Context, projectKey string) error {
	_, err := q.exec(ctx, q.deleteLegacyCommandConflictsStmt, deleteLegacyCommandConflicts, projectKey)
	return err
}

const getFailureMeta = `-- name: GetFailureMeta :one
SELECT signature, first_seen FROM failure_memory WHERE signature = ?
`

type GetFailureMetaRow struct {
	Signature string `json:"signature"`
	FirstSeen int64  `json:"first_seen"`
}

func (q *Queries) GetFailureMeta(ctx context.Context, signature string) (GetFailureMetaRow, error) {
	row := q.queryRow(ctx, q.getFailureMetaStmt, getFailureMeta, signature)
	var i GetFailureMetaRow
	err := row.Scan(&i.Signature, &i.FirstSeen)
	return i, err
}

const listOpenFailures = `-- name: ListOpenFailures :many
SELECT signature, cmd, cwd, headline, files, first_seen, last_seen, resolved_in, session_id, tool_call_id, repo_state, suggested, project_key, param_version, resolved_call FROM failure_memory WHERE resolved_in = '' AND project_key = ?1 ORDER BY last_seen DESC, rowid DESC LIMIT ?2
`

type ListOpenFailuresParams struct {
	ProjectKey string `json:"project_key"`
	RowLimit   int64  `json:"row_limit"`
}

func (q *Queries) ListOpenFailures(ctx context.Context, arg ListOpenFailuresParams) ([]FailureMemory, error) {
	rows, err := q.query(ctx, q.listOpenFailuresStmt, listOpenFailures, arg.ProjectKey, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailureMemory{}
	for rows.Next() {
		var i FailureMemory
		if err := rows.Scan(
			&i.Signature,
			&i.Cmd,
			&i.Cwd,
			&i.Headline,
			&i.Files,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ResolvedIn,
			&i.SessionID,
			&i.ToolCallID,
			&i.RepoState,
			&i.Suggested,
			&i.ProjectKey,
			&i.ParamVersion,
			&i.ResolvedCall,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCommands = `-- name: ListRecentCommands :many
SELECT cmd_norm, cwd, kind, last_exit, last_at, ok_count, fail_count, last_session_id, last_tool_call_id, repo_state, suggested, project_key, param_version FROM command_memory WHERE project_key = ?1 ORDER BY last_at DESC, rowid DESC LIMIT ?2
`

type ListRecentCommandsParams struct {
	ProjectKey string `json:"project_key"`
	RowLimit   int64  `json:"row_limit"`
}

// last_at is millisecond-granularity so re-runs order by recency;
// rowid settles ties for rows written in the same millisecond.
// project_key is an admissibility clause, not a ranking signal: a
// candidate from another partition is inadmissible before relevance
// ever runs.
func (q *Queries) ListRecentCommands(ctx context.Context, arg ListRecentCommandsParams) ([]CommandMemory, error) {
	rows, err := q.query(ctx, q.listRecentCommandsStmt, listRecentCommands, arg.ProjectKey, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommandMemory{}
	for rows.Next() {
		var i CommandMemory
		if err := rows.Scan(
			&i.CmdNorm,
			&i.Cwd,
			&i.Kind,
			&i.LastExit,
			&i.LastAt,
			&i.OkCount,
			&i.FailCount,
			&i.LastSessionID,
			&i.LastToolCallID,
			&i.RepoState,
			&i.Suggested,
			&i.ProjectKey,
			&i.ParamVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolvedFailures = `-- name: ListResolvedFailures :many
SELECT signature, cmd, cwd, headline, files, first_seen, last_seen, resolved_in, session_id, tool_call_id, repo_state, suggested, project_key, param_version, resolved_call FROM failure_memory WHERE resolved_in != '' AND project_key = ?1 ORDER BY last_seen DESC, rowid DESC LIMIT ?2
`

type ListResolvedFailuresParams struct {
	ProjectKey string `json:"project_key"`
	RowLimit   int64  `json:"row_limit"`
}

// Resolved rows are knowledge, not warnings: the failure signature
// and when it last saw a clean run. Ordered by last_seen (the last
// failing observation), not resolution time -- the row's freshness
// is still about when the failure was last real.
func (q *Queries) ListResolvedFailures(ctx context.Context, arg ListResolvedFailuresParams) ([]FailureMemory, error) {
	rows, err := q.query(ctx, q.listResolvedFailuresStmt, listResolvedFailures, arg.ProjectKey, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailureMemory{}
	for rows.Next() {
		var i FailureMemory
		if err := rows.Scan(
			&i.Signature,
			&i.Cmd,
			&i.Cwd,
			&i.Headline,
			&i.Files,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ResolvedIn,
			&i.SessionID,
			&i.ToolCallID,
			&i.RepoState,
			&i.Suggested,
			&i.ProjectKey,
			&i.ParamVersion,
			&i.ResolvedCall,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionOpenFailures = `-- name: ListSessionOpenFailures :many
SELECT f.signature, f.cmd, f.cwd, f.headline, f.files, f.first_seen, f.last_seen, f.resolved_in, f.session_id, f.tool_call_id, f.repo_state, f.suggested, f.project_key, f.param_version, f.resolved_call
FROM failure_memory f
INNER JOIN command_memory c
    ON c.cmd_norm = f.cmd
    AND c.cwd = f.cwd
WHERE f.resolved_in = ''
    AND f.project_key = ?1
    AND c.project_key = ?1
    AND c.last_session_id IN (
        SELECT id FROM sessions
        WHERE id = ?2 OR parent_session_id = ?2
    )
    AND c.last_exit > 0
ORDER BY f.last_seen DESC, f.rowid DESC
LIMIT 50
`

type ListSessionOpenFailuresParams struct {
	ProjectKey string `json:"project_key"`
	SessionID  string `json:"session_id"`
}

// Open failure rows whose commands the given session (or one of its
// task-tool child sessions) last ran and last failed: the reconcile
// edge's "observed and left open" set. A sub-agent's bash records
// under the child session ID; without the children subquery those
// rows would reconcile to no one -- the child never scans and the
// parent's delegation produced the mess. One level only, matching
// the task tool's nesting depth. command_memory's last_session_id
// is last-writer, so a row another session re-ran more recently
// drops out of this session's set even while it stays open; a
// concurrently opened row the run never invoked can never flag here.
// Same bound as the tail's fetch pool -- a session can observe more
// distinct commands than this only pathologically, and the retry
// prompt renders at most ten.
func (q *Queries) ListSessionOpenFailures(ctx context.Context, arg ListSessionOpenFailuresParams) ([]FailureMemory, error) {
	rows, err := q.query(ctx, q.listSessionOpenFailuresStmt, listSessionOpenFailures, arg.ProjectKey, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailureMemory{}
	for rows.Next() {
		var i FailureMemory
		if err := rows.Scan(
			&i.Signature,
			&i.Cmd,
			&i.Cwd,
			&i.Headline,
			&i.Files,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ResolvedIn,
			&i.SessionID,
			&i.ToolCallID,
			&i.RepoState,
			&i.Suggested,
			&i.ProjectKey,
			&i.ParamVersion,
			&i.ResolvedCall,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclaimedFailures = `-- name: ListUnclaimedFailures :many
SELECT signature, cmd, cwd, headline, first_seen
FROM failure_memory WHERE project_key = ''
`

type ListUnclaimedFailuresRow struct {
	Signature string `json:"signature"`
	Cmd       string `json:"cmd"`
	Cwd       string `json:"cwd"`
	Headline  string `json:"headline"`
	FirstSeen int64  `json:"first_seen"`
}

// Legacy failure rows awaiting a partition claim (pre-provenance
// writes). The claim re-keys them Go-side because the signature hash
// itself carries project_key -- a column UPDATE alone would leave a
// stale PK, and the next occurrence of the same failure would open a
// second row.
func (q *Queries) ListUnclaimedFailures(ctx context.Context) ([]ListUnclaimedFailuresRow, error) {
	rows, err := q.query(ctx, q.listUnclaimedFailuresStmt, listUnclaimedFailures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnclaimedFailuresRow{}
	for rows.Next() {
		var i ListUnclaimedFailuresRow
		if err := rows.Scan(
			&i.Signature,
			&i.Cmd,
			&i.Cwd,
			&i.Headline,
			&i.FirstSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeFailureFirstSeen = `-- name: MergeFailureFirstSeen :exec
UPDATE failure_memory SET first_seen = ? WHERE signature = ?
`

type MergeFailureFirstSeenParams struct {
	FirstSeen int64  `json:"first_seen"`
	Signature string `json:"signature"`
}

// A claimed row colliding with an already-partitioned twin keeps the
// twin (fresher provenance) but the failure's true age survives --
// the caller passes min(twin.first_seen, legacy.first_seen).
func (q *Queries) MergeFailureFirstSeen(ctx context.Context, arg MergeFailureFirstSeenParams) error {
	_, err := q.exec(ctx, q.mergeFailureFirstSeenStmt, mergeFailureFirstSeen, arg.FirstSeen, arg.Signature)
	return err
}

const rekeyFailurePartition = `-- name: RekeyFailurePartition :exec
UPDATE failure_memory SET signature = ?, project_key = ? WHERE signature = ?
`

type RekeyFailurePartitionParams struct {
	Signature   string `json:"signature"`
	ProjectKey  string `json:"project_key"`
	Signature_2 string `json:"signature_2"`
}

// Claim one legacy row onto its partitioned signature.
func (q *Queries) RekeyFailurePartition(ctx context.Context, arg RekeyFailurePartitionParams) error {
	_, err := q.exec(ctx, q.rekeyFailurePartitionStmt, rekeyFailurePartition, arg.Signature, arg.ProjectKey, arg.Signature_2)
	return err
}

const resolveFailuresForCommand = `-- name: ResolveFailuresForCommand :exec
UPDATE failure_memory SET
    resolved_in = ?,
    resolved_call = ?
WHERE cmd = ? AND cwd = ? AND resolved_in = '' AND project_key = ?
`

type ResolveFailuresForCommandParams struct {
	ResolvedIn   string `json:"resolved_in"`
	ResolvedCall string `json:"resolved_call"`
	Cmd          string `json:"cmd"`
	Cwd          string `json:"cwd"`
	ProjectKey   string `json:"project_key"`
}

// A clean run of a normalized command resolves its open failure rows
// in the same directory -- "go test ./..." passing in packages/web
// does not close packages/api's failure. resolved_call names the
// call that carried the clean verdict, where detectable. The
// resolution is partition-scoped like every read: one project's
// green run cannot close another's observation.
func (q *Queries) ResolveFailuresForCommand(ctx context.Context, arg ResolveFailuresForCommandParams) error {
	_, err := q.exec(ctx, q.resolveFailuresForCommandStmt, resolveFailuresForCommand,
		arg.ResolvedIn,
		arg.ResolvedCall,
		arg.Cmd,
		arg.Cwd,
		arg.ProjectKey,
	)
	return err
}

const upsertCommandRun = `-- name: UpsertCommandRun :exec
INSERT INTO command_memory (
    cmd_norm,
    cwd,
    kind,
    last_exit,
    last_at,
    ok_count,
    fail_count,
    last_session_id,
    last_tool_call_id,
    repo_state,
    suggested,
    project_key,
    param_version
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) ON CONFLICT(cmd_norm, cwd, project_key) DO UPDATE SET
    kind = CASE WHEN excluded.last_exit >= 0 THEN excluded.kind ELSE command_memory.kind END,
    -- Interrupted runs carry last_exit = -1: the run is noted but
    -- never overwrites the command's last real verdict -- nor the
    -- session stamp, which must stay with the last verdict's writer
    -- so a denied or killed re-run cannot disown the observing
    -- session (or claim a failing verdict it never saw). The
    -- observation provenance rides the same guard: it describes the
    -- last real verdict, so a verdictless run must not re-stamp it.
    last_exit = CASE WHEN excluded.last_exit >= 0 THEN excluded.last_exit ELSE command_memory.last_exit END,
    last_at = CASE WHEN excluded.last_exit >= 0 THEN excluded.last_at ELSE command_memory.last_at END,
    ok_count = command_memory.ok_count + excluded.ok_count,
    fail_count = command_memory.fail_count + excluded.fail_count,
    last_session_id = CASE WHEN excluded.last_exit >= 0 THEN excluded.last_session_id ELSE command_memory.last_session_id END,
    last_tool_call_id = CASE WHEN excluded.last_exit >= 0 THEN excluded.last_tool_call_id ELSE command_memory.last_tool_call_id END,
    repo_state = CASE WHEN excluded.last_exit >= 0 THEN excluded.repo_state ELSE command_memory.repo_state END,
    suggested = CASE WHEN excluded.last_exit >= 0 THEN excluded.suggested ELSE command_memory.suggested END,
    -- Partition and params-in-force are not verdict properties: the
    -- latest writer's are always authoritative.
    project_key = excluded.project_key,
    param_version = excluded.param_version
`

type UpsertCommandRunParams struct {
	CmdNorm        string `json:"cmd_norm"`
	Cwd            string `json:"cwd"`
	Kind           string `json:"kind"`
	LastExit       int64  `json:"last_exit"`
	LastAt         int64  `json:"last_at"`
	OkCount        int64  `json:"ok_count"`
	FailCount      int64  `json:"fail_count"`
	LastSessionID  string `json:"last_session_id"`
	LastToolCallID string `json:"last_tool_call_id"`
	RepoState      string `json:"repo_state"`
	Suggested      int64  `json:"suggested"`
	ProjectKey     string `json:"project_key"`
	ParamVersion   string `json:"param_version"`
}

// Project-scoped command ledger: one row per normalized command,
// shared across sessions. ok/fail counts merge additively so the row
// is the running tally, not a per-session sample.
func (q *Queries) UpsertCommandRun(ctx context.Context, arg UpsertCommandRunParams) error {
	_, err := q.exec(ctx, q.upsertCommandRunStmt, upsertCommandRun,
		arg.CmdNorm,
		arg.Cwd,
		arg.Kind,
		arg.LastExit,
		arg.LastAt,
		arg.OkCount,
		arg.FailCount,
		arg.LastSessionID,
		arg.LastToolCallID,
		arg.RepoState,
		arg.Suggested,
		arg.ProjectKey,
		arg.ParamVersion,
	)
	return err
}

const upsertFailure = `-- name: UpsertFailure :exec
INSERT INTO failure_memory (
    signature,
    cmd,
    cwd,
    headline,
    files,
    first_seen,
    last_seen,
    session_id,
    tool_call_id,
    repo_state,
    suggested,
    project_key,
    param_version
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) ON CONFLICT(signature) DO UPDATE SET
    headline = excluded.headline,
    files = excluded.files,
    -- first_seen stamps the open epoch, not the original birth: a
    -- resurrected row (was resolved) counts as newly introduced, a
    -- continuously-open re-fail keeps its first observation.
    first_seen = CASE WHEN failure_memory.resolved_in != '' THEN excluded.first_seen ELSE failure_memory.first_seen END,
    last_seen = excluded.last_seen,
    session_id = excluded.session_id,
    tool_call_id = excluded.tool_call_id,
    repo_state = excluded.repo_state,
    suggested = excluded.suggested,
    project_key = excluded.project_key,
    param_version = excluded.param_version,
    resolved_in = '',
    -- A re-fail clears the old resolution lineage: the row's open
    -- epoch is new, so who closed the previous epoch is history.
    resolved_call = ''
`

type UpsertFailureParams struct {
	Signature    string `json:"signature"`
	Cmd          string `json:"cmd"`
	Cwd          string `json:"cwd"`
	Headline     string `json:"headline"`
	Files        string `json:"files"`
	FirstSeen    int64  `json:"first_seen"`
	LastSeen     int64  `json:"last_seen"`
	SessionID    string `json:"session_id"`
	ToolCallID   string `json:"tool_call_id"`
	RepoState    string `json:"repo_state"`
	Suggested    int64  `json:"suggested"`
	ProjectKey   string `json:"project_key"`
	ParamVersion string `json:"param_version"`
}

// One row per (normalized command, directory, error headline)
// signature. A re-fail refreshes the observation -- headline, file
// hints, and the observation's provenance all move with the latest
// failure, not the first.
func (q *Queries) UpsertFailure(ctx context.Context, arg UpsertFailureParams) error {
	_, err := q.exec(ctx, q.upsertFailureStmt, upsertFailure,
		arg.Signature,
		arg.Cmd,
		arg.Cwd,
		arg.Headline,
		arg.Files,
		arg.FirstSeen,
		arg.LastSeen,
		arg.SessionID,
		arg.ToolCallID,
		arg.RepoState,
		arg.Suggested,
		arg.ProjectKey,
		arg.ParamVersion,
	)
	return err
}
