// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commands.sql

package db

import (
	"context"
)

const listOpenFailures = `-- name: ListOpenFailures :many
SELECT signature, cmd, cwd, headline, files, first_seen, last_seen, resolved_in FROM failure_memory WHERE resolved_in = '' ORDER BY last_seen DESC, rowid DESC LIMIT ?
`

func (q *Queries) ListOpenFailures(ctx context.Context, limit int64) ([]FailureMemory, error) {
	rows, err := q.query(ctx, q.listOpenFailuresStmt, listOpenFailures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailureMemory{}
	for rows.Next() {
		var i FailureMemory
		if err := rows.Scan(
			&i.Signature,
			&i.Cmd,
			&i.Cwd,
			&i.Headline,
			&i.Files,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ResolvedIn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCommands = `-- name: ListRecentCommands :many
SELECT cmd_norm, cwd, kind, last_exit, last_at, ok_count, fail_count, last_session_id FROM command_memory ORDER BY last_at DESC, rowid DESC LIMIT ?
`

// last_at is millisecond-granularity so re-runs order by recency;
// rowid settles ties for rows written in the same millisecond.
func (q *Queries) ListRecentCommands(ctx context.Context, limit int64) ([]CommandMemory, error) {
	rows, err := q.query(ctx, q.listRecentCommandsStmt, listRecentCommands, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommandMemory{}
	for rows.Next() {
		var i CommandMemory
		if err := rows.Scan(
			&i.CmdNorm,
			&i.Cwd,
			&i.Kind,
			&i.LastExit,
			&i.LastAt,
			&i.OkCount,
			&i.FailCount,
			&i.LastSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveFailuresForCommand = `-- name: ResolveFailuresForCommand :exec
UPDATE failure_memory SET
    resolved_in = ?
WHERE cmd = ? AND cwd = ? AND resolved_in = ''
`

type ResolveFailuresForCommandParams struct {
	ResolvedIn string `json:"resolved_in"`
	Cmd        string `json:"cmd"`
	Cwd        string `json:"cwd"`
}

// A clean run of a normalized command resolves its open failure rows
// in the same directory -- "go test ./..." passing in packages/web
// does not close packages/api's failure.
func (q *Queries) ResolveFailuresForCommand(ctx context.Context, arg ResolveFailuresForCommandParams) error {
	_, err := q.exec(ctx, q.resolveFailuresForCommandStmt, resolveFailuresForCommand, arg.ResolvedIn, arg.Cmd, arg.Cwd)
	return err
}

const upsertCommandRun = `-- name: UpsertCommandRun :exec
INSERT INTO command_memory (
    cmd_norm,
    cwd,
    kind,
    last_exit,
    last_at,
    ok_count,
    fail_count,
    last_session_id
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) ON CONFLICT(cmd_norm, cwd) DO UPDATE SET
    kind = excluded.kind,
    -- Interrupted runs carry last_exit = -1: the run is noted but
    -- never overwrites the command's last real verdict.
    last_exit = CASE WHEN excluded.last_exit >= 0 THEN excluded.last_exit ELSE command_memory.last_exit END,
    last_at = excluded.last_at,
    ok_count = command_memory.ok_count + excluded.ok_count,
    fail_count = command_memory.fail_count + excluded.fail_count,
    last_session_id = excluded.last_session_id
`

type UpsertCommandRunParams struct {
	CmdNorm       string `json:"cmd_norm"`
	Cwd           string `json:"cwd"`
	Kind          string `json:"kind"`
	LastExit      int64  `json:"last_exit"`
	LastAt        int64  `json:"last_at"`
	OkCount       int64  `json:"ok_count"`
	FailCount     int64  `json:"fail_count"`
	LastSessionID string `json:"last_session_id"`
}

// Project-scoped command ledger: one row per normalized command,
// shared across sessions. ok/fail counts merge additively so the row
// is the running tally, not a per-session sample.
func (q *Queries) UpsertCommandRun(ctx context.Context, arg UpsertCommandRunParams) error {
	_, err := q.exec(ctx, q.upsertCommandRunStmt, upsertCommandRun,
		arg.CmdNorm,
		arg.Cwd,
		arg.Kind,
		arg.LastExit,
		arg.LastAt,
		arg.OkCount,
		arg.FailCount,
		arg.LastSessionID,
	)
	return err
}

const upsertFailure = `-- name: UpsertFailure :exec
INSERT INTO failure_memory (
    signature,
    cmd,
    cwd,
    headline,
    files,
    first_seen,
    last_seen
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) ON CONFLICT(signature) DO UPDATE SET
    headline = excluded.headline,
    files = excluded.files,
    last_seen = excluded.last_seen,
    resolved_in = ''
`

type UpsertFailureParams struct {
	Signature string `json:"signature"`
	Cmd       string `json:"cmd"`
	Cwd       string `json:"cwd"`
	Headline  string `json:"headline"`
	Files     string `json:"files"`
	FirstSeen int64  `json:"first_seen"`
	LastSeen  int64  `json:"last_seen"`
}

// One row per (normalized command, directory, error headline)
// signature. A re-fail refreshes the observation -- headline and
// file hints move with the latest failure, not the first.
func (q *Queries) UpsertFailure(ctx context.Context, arg UpsertFailureParams) error {
	_, err := q.exec(ctx, q.upsertFailureStmt, upsertFailure,
		arg.Signature,
		arg.Cmd,
		arg.Cwd,
		arg.Headline,
		arg.Files,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
