// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.bumpSessionCounterStmt, err = db.PrepareContext(ctx, bumpSessionCounter); err != nil {
		return nil, fmt.Errorf("error preparing query BumpSessionCounter: %w", err)
	}
	if q.countCleanReferentAcceptancesStmt, err = db.PrepareContext(ctx, countCleanReferentAcceptances); err != nil {
		return nil, fmt.Errorf("error preparing query CountCleanReferentAcceptances: %w", err)
	}
	if q.countUserMessagesBySessionStmt, err = db.PrepareContext(ctx, countUserMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountUserMessagesBySession: %w", err)
	}
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createNotebookEntryStmt, err = db.PrepareContext(ctx, createNotebookEntry); err != nil {
		return nil, fmt.Errorf("error preparing query CreateNotebookEntry: %w", err)
	}
	if q.createNotebookTagStmt, err = db.PrepareContext(ctx, createNotebookTag); err != nil {
		return nil, fmt.Errorf("error preparing query CreateNotebookTag: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteCommandConflictsStmt, err = db.PrepareContext(ctx, deleteCommandConflicts); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCommandConflicts: %w", err)
	}
	if q.deleteFailureStmt, err = db.PrepareContext(ctx, deleteFailure); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFailure: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMCPDisabledServerStmt, err = db.PrepareContext(ctx, deleteMCPDisabledServer); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMCPDisabledServer: %w", err)
	}
	if q.deleteMCPEnabledServerStmt, err = db.PrepareContext(ctx, deleteMCPEnabledServer); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMCPEnabledServer: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteNotebookEntriesBySessionStmt, err = db.PrepareContext(ctx, deleteNotebookEntriesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNotebookEntriesBySession: %w", err)
	}
	if q.deleteProcessedSegmentsBySessionStmt, err = db.PrepareContext(ctx, deleteProcessedSegmentsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProcessedSegmentsBySession: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionDigestStmt, err = db.PrepareContext(ctx, deleteSessionDigest); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionDigest: %w", err)
	}
	if q.deleteSessionDigestIndexStmt, err = db.PrepareContext(ctx, deleteSessionDigestIndex); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionDigestIndex: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.getAverageResponseTimeStmt, err = db.PrepareContext(ctx, getAverageResponseTime); err != nil {
		return nil, fmt.Errorf("error preparing query GetAverageResponseTime: %w", err)
	}
	if q.getCollapsedTurnStatsStmt, err = db.PrepareContext(ctx, getCollapsedTurnStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetCollapsedTurnStats: %w", err)
	}
	if q.getEdgeFiringStatsStmt, err = db.PrepareContext(ctx, getEdgeFiringStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetEdgeFiringStats: %w", err)
	}
	if q.getFailureMetaStmt, err = db.PrepareContext(ctx, getFailureMeta); err != nil {
		return nil, fmt.Errorf("error preparing query GetFailureMeta: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getFileReadStmt, err = db.PrepareContext(ctx, getFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileRead: %w", err)
	}
	if q.getHourDayHeatmapStmt, err = db.PrepareContext(ctx, getHourDayHeatmap); err != nil {
		return nil, fmt.Errorf("error preparing query GetHourDayHeatmap: %w", err)
	}
	if q.getLastAssistantMessageBySessionStmt, err = db.PrepareContext(ctx, getLastAssistantMessageBySession); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastAssistantMessageBySession: %w", err)
	}
	if q.getLastSessionStmt, err = db.PrepareContext(ctx, getLastSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastSession: %w", err)
	}
	if q.getLatestCheckpointEntryStmt, err = db.PrepareContext(ctx, getLatestCheckpointEntry); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestCheckpointEntry: %w", err)
	}
	if q.getMapUsageStmt, err = db.PrepareContext(ctx, getMapUsage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMapUsage: %w", err)
	}
	if q.getMaxNotebookEventNumberStmt, err = db.PrepareContext(ctx, getMaxNotebookEventNumber); err != nil {
		return nil, fmt.Errorf("error preparing query GetMaxNotebookEventNumber: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getNotebookEntriesStmt, err = db.PrepareContext(ctx, getNotebookEntries); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotebookEntries: %w", err)
	}
	if q.getNotebookEntriesByEventTypeStmt, err = db.PrepareContext(ctx, getNotebookEntriesByEventType); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotebookEntriesByEventType: %w", err)
	}
	if q.getNotebookEntriesByTurnStmt, err = db.PrepareContext(ctx, getNotebookEntriesByTurn); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotebookEntriesByTurn: %w", err)
	}
	if q.getNotebookEntriesByTurnSegmentStmt, err = db.PrepareContext(ctx, getNotebookEntriesByTurnSegment); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotebookEntriesByTurnSegment: %w", err)
	}
	if q.getNotebookEntryCountStmt, err = db.PrepareContext(ctx, getNotebookEntryCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotebookEntryCount: %w", err)
	}
	if q.getNotebookTagsByEntryStmt, err = db.PrepareContext(ctx, getNotebookTagsByEntry); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotebookTagsByEntry: %w", err)
	}
	if q.getNotebookTokenCountStmt, err = db.PrepareContext(ctx, getNotebookTokenCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotebookTokenCount: %w", err)
	}
	if q.getNotebookTurnsWithEntriesStmt, err = db.PrepareContext(ctx, getNotebookTurnsWithEntries); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotebookTurnsWithEntries: %w", err)
	}
	if q.getOldestNotebookEntriesStmt, err = db.PrepareContext(ctx, getOldestNotebookEntries); err != nil {
		return nil, fmt.Errorf("error preparing query GetOldestNotebookEntries: %w", err)
	}
	if q.getProcessedSegmentStmt, err = db.PrepareContext(ctx, getProcessedSegment); err != nil {
		return nil, fmt.Errorf("error preparing query GetProcessedSegment: %w", err)
	}
	if q.getProjectRateStmt, err = db.PrepareContext(ctx, getProjectRate); err != nil {
		return nil, fmt.Errorf("error preparing query GetProjectRate: %w", err)
	}
	if q.getPruningStatsStmt, err = db.PrepareContext(ctx, getPruningStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetPruningStats: %w", err)
	}
	if q.getRecentActivityStmt, err = db.PrepareContext(ctx, getRecentActivity); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentActivity: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getSessionCounterStmt, err = db.PrepareContext(ctx, getSessionCounter); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionCounter: %w", err)
	}
	if q.getSessionDigestStmt, err = db.PrepareContext(ctx, getSessionDigest); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionDigest: %w", err)
	}
	if q.getToolUsageStmt, err = db.PrepareContext(ctx, getToolUsage); err != nil {
		return nil, fmt.Errorf("error preparing query GetToolUsage: %w", err)
	}
	if q.getTotalStatsStmt, err = db.PrepareContext(ctx, getTotalStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalStats: %w", err)
	}
	if q.getUsageByDayStmt, err = db.PrepareContext(ctx, getUsageByDay); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDay: %w", err)
	}
	if q.getUsageByDayOfWeekStmt, err = db.PrepareContext(ctx, getUsageByDayOfWeek); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDayOfWeek: %w", err)
	}
	if q.getUsageByHourStmt, err = db.PrepareContext(ctx, getUsageByHour); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByHour: %w", err)
	}
	if q.getUsageByModelStmt, err = db.PrepareContext(ctx, getUsageByModel); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByModel: %w", err)
	}
	if q.indexSessionDigestStmt, err = db.PrepareContext(ctx, indexSessionDigest); err != nil {
		return nil, fmt.Errorf("error preparing query IndexSessionDigest: %w", err)
	}
	if q.insertEdgeFiringStmt, err = db.PrepareContext(ctx, insertEdgeFiring); err != nil {
		return nil, fmt.Errorf("error preparing query InsertEdgeFiring: %w", err)
	}
	if q.insertMCPDisabledServerStmt, err = db.PrepareContext(ctx, insertMCPDisabledServer); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMCPDisabledServer: %w", err)
	}
	if q.insertMCPEnabledServerStmt, err = db.PrepareContext(ctx, insertMCPEnabledServer); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMCPEnabledServer: %w", err)
	}
	if q.insertReferentEpisodeStmt, err = db.PrepareContext(ctx, insertReferentEpisode); err != nil {
		return nil, fmt.Errorf("error preparing query InsertReferentEpisode: %w", err)
	}
	if q.labelReferentEpisodeStmt, err = db.PrepareContext(ctx, labelReferentEpisode); err != nil {
		return nil, fmt.Errorf("error preparing query LabelReferentEpisode: %w", err)
	}
	if q.listAllUserMessagesStmt, err = db.PrepareContext(ctx, listAllUserMessages); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllUserMessages: %w", err)
	}
	if q.listCommandPartitionKeysStmt, err = db.PrepareContext(ctx, listCommandPartitionKeys); err != nil {
		return nil, fmt.Errorf("error preparing query ListCommandPartitionKeys: %w", err)
	}
	if q.listFailurePartitionKeysStmt, err = db.PrepareContext(ctx, listFailurePartitionKeys); err != nil {
		return nil, fmt.Errorf("error preparing query ListFailurePartitionKeys: %w", err)
	}
	if q.listFailuresByKeyStmt, err = db.PrepareContext(ctx, listFailuresByKey); err != nil {
		return nil, fmt.Errorf("error preparing query ListFailuresByKey: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listHotReadFilesStmt, err = db.PrepareContext(ctx, listHotReadFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListHotReadFiles: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMCPDisabledServersStmt, err = db.PrepareContext(ctx, listMCPDisabledServers); err != nil {
		return nil, fmt.Errorf("error preparing query ListMCPDisabledServers: %w", err)
	}
	if q.listMCPEnabledServersStmt, err = db.PrepareContext(ctx, listMCPEnabledServers); err != nil {
		return nil, fmt.Errorf("error preparing query ListMCPEnabledServers: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listMessagesBySessionFromSummaryStmt, err = db.PrepareContext(ctx, listMessagesBySessionFromSummary); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySessionFromSummary: %w", err)
	}
	if q.listNewFilesStmt, err = db.PrepareContext(ctx, listNewFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListNewFiles: %w", err)
	}
	if q.listOpenFailuresStmt, err = db.PrepareContext(ctx, listOpenFailures); err != nil {
		return nil, fmt.Errorf("error preparing query ListOpenFailures: %w", err)
	}
	if q.listPendingReferentLabelsStmt, err = db.PrepareContext(ctx, listPendingReferentLabels); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingReferentLabels: %w", err)
	}
	if q.listProcessedSegmentsStmt, err = db.PrepareContext(ctx, listProcessedSegments); err != nil {
		return nil, fmt.Errorf("error preparing query ListProcessedSegments: %w", err)
	}
	if q.listRecentCommandsStmt, err = db.PrepareContext(ctx, listRecentCommands); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentCommands: %w", err)
	}
	if q.listRecentSessionDigestsStmt, err = db.PrepareContext(ctx, listRecentSessionDigests); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentSessionDigests: %w", err)
	}
	if q.listReferentCalibrationEpisodesStmt, err = db.PrepareContext(ctx, listReferentCalibrationEpisodes); err != nil {
		return nil, fmt.Errorf("error preparing query ListReferentCalibrationEpisodes: %w", err)
	}
	if q.listReferentPriorEventsStmt, err = db.PrepareContext(ctx, listReferentPriorEvents); err != nil {
		return nil, fmt.Errorf("error preparing query ListReferentPriorEvents: %w", err)
	}
	if q.listReferentRateEventsStmt, err = db.PrepareContext(ctx, listReferentRateEvents); err != nil {
		return nil, fmt.Errorf("error preparing query ListReferentRateEvents: %w", err)
	}
	if q.listReferentsForPhrasesStmt, err = db.PrepareContext(ctx, listReferentsForPhrases); err != nil {
		return nil, fmt.Errorf("error preparing query ListReferentsForPhrases: %w", err)
	}
	if q.listResolvedFailuresStmt, err = db.PrepareContext(ctx, listResolvedFailures); err != nil {
		return nil, fmt.Errorf("error preparing query ListResolvedFailures: %w", err)
	}
	if q.listSessionCountersStmt, err = db.PrepareContext(ctx, listSessionCounters); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionCounters: %w", err)
	}
	if q.listSessionOpenFailuresStmt, err = db.PrepareContext(ctx, listSessionOpenFailures); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionOpenFailures: %w", err)
	}
	if q.listSessionReadFilesStmt, err = db.PrepareContext(ctx, listSessionReadFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionReadFiles: %w", err)
	}
	if q.listSessionTestVerdictsStmt, err = db.PrepareContext(ctx, listSessionTestVerdicts); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionTestVerdicts: %w", err)
	}
	if q.listSessionTouchedPathsStmt, err = db.PrepareContext(ctx, listSessionTouchedPaths); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionTouchedPaths: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listStaleDigestSessionsStmt, err = db.PrepareContext(ctx, listStaleDigestSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListStaleDigestSessions: %w", err)
	}
	if q.listUnclaimedFailuresStmt, err = db.PrepareContext(ctx, listUnclaimedFailures); err != nil {
		return nil, fmt.Errorf("error preparing query ListUnclaimedFailures: %w", err)
	}
	if q.listUserMessagesBySessionStmt, err = db.PrepareContext(ctx, listUserMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserMessagesBySession: %w", err)
	}
	if q.markReferentEventsFoldedStmt, err = db.PrepareContext(ctx, markReferentEventsFolded); err != nil {
		return nil, fmt.Errorf("error preparing query MarkReferentEventsFolded: %w", err)
	}
	if q.markSegmentProcessedStmt, err = db.PrepareContext(ctx, markSegmentProcessed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkSegmentProcessed: %w", err)
	}
	if q.mergeFailureFirstSeenStmt, err = db.PrepareContext(ctx, mergeFailureFirstSeen); err != nil {
		return nil, fmt.Errorf("error preparing query MergeFailureFirstSeen: %w", err)
	}
	if q.promoteReferentStmt, err = db.PrepareContext(ctx, promoteReferent); err != nil {
		return nil, fmt.Errorf("error preparing query PromoteReferent: %w", err)
	}
	if q.recordCollapsedTurnStmt, err = db.PrepareContext(ctx, recordCollapsedTurn); err != nil {
		return nil, fmt.Errorf("error preparing query RecordCollapsedTurn: %w", err)
	}
	if q.recordFileReadStmt, err = db.PrepareContext(ctx, recordFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query RecordFileRead: %w", err)
	}
	if q.recordProcessedSegmentStmt, err = db.PrepareContext(ctx, recordProcessedSegment); err != nil {
		return nil, fmt.Errorf("error preparing query RecordProcessedSegment: %w", err)
	}
	if q.recordSegmentAttemptStmt, err = db.PrepareContext(ctx, recordSegmentAttempt); err != nil {
		return nil, fmt.Errorf("error preparing query RecordSegmentAttempt: %w", err)
	}
	if q.rekeyCommandPartitionStmt, err = db.PrepareContext(ctx, rekeyCommandPartition); err != nil {
		return nil, fmt.Errorf("error preparing query RekeyCommandPartition: %w", err)
	}
	if q.rekeyFailurePartitionStmt, err = db.PrepareContext(ctx, rekeyFailurePartition); err != nil {
		return nil, fmt.Errorf("error preparing query RekeyFailurePartition: %w", err)
	}
	if q.renameSessionStmt, err = db.PrepareContext(ctx, renameSession); err != nil {
		return nil, fmt.Errorf("error preparing query RenameSession: %w", err)
	}
	if q.resolveFailuresForCommandStmt, err = db.PrepareContext(ctx, resolveFailuresForCommand); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveFailuresForCommand: %w", err)
	}
	if q.searchNotebookByTagStmt, err = db.PrepareContext(ctx, searchNotebookByTag); err != nil {
		return nil, fmt.Errorf("error preparing query SearchNotebookByTag: %w", err)
	}
	if q.searchNotebookByTextStmt, err = db.PrepareContext(ctx, searchNotebookByText); err != nil {
		return nil, fmt.Errorf("error preparing query SearchNotebookByText: %w", err)
	}
	if q.searchSessionDigestsStmt, err = db.PrepareContext(ctx, searchSessionDigests); err != nil {
		return nil, fmt.Errorf("error preparing query SearchSessionDigests: %w", err)
	}
	if q.setSessionChannelStmt, err = db.PrepareContext(ctx, setSessionChannel); err != nil {
		return nil, fmt.Errorf("error preparing query SetSessionChannel: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateNotebookCompressionStmt, err = db.PrepareContext(ctx, updateNotebookCompression); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateNotebookCompression: %w", err)
	}
	if q.updateReferentEpisodeLabelStmt, err = db.PrepareContext(ctx, updateReferentEpisodeLabel); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateReferentEpisodeLabel: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateSessionTitleAndUsageStmt, err = db.PrepareContext(ctx, updateSessionTitleAndUsage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionTitleAndUsage: %w", err)
	}
	if q.upsertCommandRunStmt, err = db.PrepareContext(ctx, upsertCommandRun); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertCommandRun: %w", err)
	}
	if q.upsertFailureStmt, err = db.PrepareContext(ctx, upsertFailure); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertFailure: %w", err)
	}
	if q.upsertProjectRateStmt, err = db.PrepareContext(ctx, upsertProjectRate); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertProjectRate: %w", err)
	}
	if q.upsertSessionDigestStmt, err = db.PrepareContext(ctx, upsertSessionDigest); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSessionDigest: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.bumpSessionCounterStmt != nil {
		if cerr := q.bumpSessionCounterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing bumpSessionCounterStmt: %w", cerr)
		}
	}
	if q.countCleanReferentAcceptancesStmt != nil {
		if cerr := q.countCleanReferentAcceptancesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCleanReferentAcceptancesStmt: %w", cerr)
		}
	}
	if q.countUserMessagesBySessionStmt != nil {
		if cerr := q.countUserMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUserMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createNotebookEntryStmt != nil {
		if cerr := q.createNotebookEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNotebookEntryStmt: %w", cerr)
		}
	}
	if q.createNotebookTagStmt != nil {
		if cerr := q.createNotebookTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNotebookTagStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteCommandConflictsStmt != nil {
		if cerr := q.deleteCommandConflictsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCommandConflictsStmt: %w", cerr)
		}
	}
	if q.deleteFailureStmt != nil {
		if cerr := q.deleteFailureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFailureStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMCPDisabledServerStmt != nil {
		if cerr := q.deleteMCPDisabledServerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMCPDisabledServerStmt: %w", cerr)
		}
	}
	if q.deleteMCPEnabledServerStmt != nil {
		if cerr := q.deleteMCPEnabledServerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMCPEnabledServerStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteNotebookEntriesBySessionStmt != nil {
		if cerr := q.deleteNotebookEntriesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNotebookEntriesBySessionStmt: %w", cerr)
		}
	}
	if q.deleteProcessedSegmentsBySessionStmt != nil {
		if cerr := q.deleteProcessedSegmentsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProcessedSegmentsBySessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionDigestStmt != nil {
		if cerr := q.deleteSessionDigestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionDigestStmt: %w", cerr)
		}
	}
	if q.deleteSessionDigestIndexStmt != nil {
		if cerr := q.deleteSessionDigestIndexStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionDigestIndexStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.getAverageResponseTimeStmt != nil {
		if cerr := q.getAverageResponseTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAverageResponseTimeStmt: %w", cerr)
		}
	}
	if q.getCollapsedTurnStatsStmt != nil {
		if cerr := q.getCollapsedTurnStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCollapsedTurnStatsStmt: %w", cerr)
		}
	}
	if q.getEdgeFiringStatsStmt != nil {
		if cerr := q.getEdgeFiringStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEdgeFiringStatsStmt: %w", cerr)
		}
	}
	if q.getFailureMetaStmt != nil {
		if cerr := q.getFailureMetaStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFailureMetaStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getFileReadStmt != nil {
		if cerr := q.getFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileReadStmt: %w", cerr)
		}
	}
	if q.getHourDayHeatmapStmt != nil {
		if cerr := q.getHourDayHeatmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHourDayHeatmapStmt: %w", cerr)
		}
	}
	if q.getLastAssistantMessageBySessionStmt != nil {
		if cerr := q.getLastAssistantMessageBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastAssistantMessageBySessionStmt: %w", cerr)
		}
	}
	if q.getLastSessionStmt != nil {
		if cerr := q.getLastSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastSessionStmt: %w", cerr)
		}
	}
	if q.getLatestCheckpointEntryStmt != nil {
		if cerr := q.getLatestCheckpointEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestCheckpointEntryStmt: %w", cerr)
		}
	}
	if q.getMapUsageStmt != nil {
		if cerr := q.getMapUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMapUsageStmt: %w", cerr)
		}
	}
	if q.getMaxNotebookEventNumberStmt != nil {
		if cerr := q.getMaxNotebookEventNumberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMaxNotebookEventNumberStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getNotebookEntriesStmt != nil {
		if cerr := q.getNotebookEntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotebookEntriesStmt: %w", cerr)
		}
	}
	if q.getNotebookEntriesByEventTypeStmt != nil {
		if cerr := q.getNotebookEntriesByEventTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotebookEntriesByEventTypeStmt: %w", cerr)
		}
	}
	if q.getNotebookEntriesByTurnStmt != nil {
		if cerr := q.getNotebookEntriesByTurnStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotebookEntriesByTurnStmt: %w", cerr)
		}
	}
	if q.getNotebookEntriesByTurnSegmentStmt != nil {
		if cerr := q.getNotebookEntriesByTurnSegmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotebookEntriesByTurnSegmentStmt: %w", cerr)
		}
	}
	if q.getNotebookEntryCountStmt != nil {
		if cerr := q.getNotebookEntryCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotebookEntryCountStmt: %w", cerr)
		}
	}
	if q.getNotebookTagsByEntryStmt != nil {
		if cerr := q.getNotebookTagsByEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotebookTagsByEntryStmt: %w", cerr)
		}
	}
	if q.getNotebookTokenCountStmt != nil {
		if cerr := q.getNotebookTokenCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotebookTokenCountStmt: %w", cerr)
		}
	}
	if q.getNotebookTurnsWithEntriesStmt != nil {
		if cerr := q.getNotebookTurnsWithEntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotebookTurnsWithEntriesStmt: %w", cerr)
		}
	}
	if q.getOldestNotebookEntriesStmt != nil {
		if cerr := q.getOldestNotebookEntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOldestNotebookEntriesStmt: %w", cerr)
		}
	}
	if q.getProcessedSegmentStmt != nil {
		if cerr := q.getProcessedSegmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProcessedSegmentStmt: %w", cerr)
		}
	}
	if q.getProjectRateStmt != nil {
		if cerr := q.getProjectRateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectRateStmt: %w", cerr)
		}
	}
	if q.getPruningStatsStmt != nil {
		if cerr := q.getPruningStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPruningStatsStmt: %w", cerr)
		}
	}
	if q.getRecentActivityStmt != nil {
		if cerr := q.getRecentActivityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentActivityStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getSessionCounterStmt != nil {
		if cerr := q.getSessionCounterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionCounterStmt: %w", cerr)
		}
	}
	if q.getSessionDigestStmt != nil {
		if cerr := q.getSessionDigestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionDigestStmt: %w", cerr)
		}
	}
	if q.getToolUsageStmt != nil {
		if cerr := q.getToolUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getToolUsageStmt: %w", cerr)
		}
	}
	if q.getTotalStatsStmt != nil {
		if cerr := q.getTotalStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalStatsStmt: %w", cerr)
		}
	}
	if q.getUsageByDayStmt != nil {
		if cerr := q.getUsageByDayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayStmt: %w", cerr)
		}
	}
	if q.getUsageByDayOfWeekStmt != nil {
		if cerr := q.getUsageByDayOfWeekStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayOfWeekStmt: %w", cerr)
		}
	}
	if q.getUsageByHourStmt != nil {
		if cerr := q.getUsageByHourStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByHourStmt: %w", cerr)
		}
	}
	if q.getUsageByModelStmt != nil {
		if cerr := q.getUsageByModelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByModelStmt: %w", cerr)
		}
	}
	if q.indexSessionDigestStmt != nil {
		if cerr := q.indexSessionDigestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing indexSessionDigestStmt: %w", cerr)
		}
	}
	if q.insertEdgeFiringStmt != nil {
		if cerr := q.insertEdgeFiringStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertEdgeFiringStmt: %w", cerr)
		}
	}
	if q.insertMCPDisabledServerStmt != nil {
		if cerr := q.insertMCPDisabledServerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMCPDisabledServerStmt: %w", cerr)
		}
	}
	if q.insertMCPEnabledServerStmt != nil {
		if cerr := q.insertMCPEnabledServerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMCPEnabledServerStmt: %w", cerr)
		}
	}
	if q.insertReferentEpisodeStmt != nil {
		if cerr := q.insertReferentEpisodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertReferentEpisodeStmt: %w", cerr)
		}
	}
	if q.labelReferentEpisodeStmt != nil {
		if cerr := q.labelReferentEpisodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing labelReferentEpisodeStmt: %w", cerr)
		}
	}
	if q.listAllUserMessagesStmt != nil {
		if cerr := q.listAllUserMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllUserMessagesStmt: %w", cerr)
		}
	}
	if q.listCommandPartitionKeysStmt != nil {
		if cerr := q.listCommandPartitionKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCommandPartitionKeysStmt: %w", cerr)
		}
	}
	if q.listFailurePartitionKeysStmt != nil {
		if cerr := q.listFailurePartitionKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFailurePartitionKeysStmt: %w", cerr)
		}
	}
	if q.listFailuresByKeyStmt != nil {
		if cerr := q.listFailuresByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFailuresByKeyStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listHotReadFilesStmt != nil {
		if cerr := q.listHotReadFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listHotReadFilesStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMCPDisabledServersStmt != nil {
		if cerr := q.listMCPDisabledServersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMCPDisabledServersStmt: %w", cerr)
		}
	}
	if q.listMCPEnabledServersStmt != nil {
		if cerr := q.listMCPEnabledServersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMCPEnabledServersStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionFromSummaryStmt != nil {
		if cerr := q.listMessagesBySessionFromSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionFromSummaryStmt: %w", cerr)
		}
	}
	if q.listNewFilesStmt != nil {
		if cerr := q.listNewFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNewFilesStmt: %w", cerr)
		}
	}
	if q.listOpenFailuresStmt != nil {
		if cerr := q.listOpenFailuresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOpenFailuresStmt: %w", cerr)
		}
	}
	if q.listPendingReferentLabelsStmt != nil {
		if cerr := q.listPendingReferentLabelsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingReferentLabelsStmt: %w", cerr)
		}
	}
	if q.listProcessedSegmentsStmt != nil {
		if cerr := q.listProcessedSegmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProcessedSegmentsStmt: %w", cerr)
		}
	}
	if q.listRecentCommandsStmt != nil {
		if cerr := q.listRecentCommandsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentCommandsStmt: %w", cerr)
		}
	}
	if q.listRecentSessionDigestsStmt != nil {
		if cerr := q.listRecentSessionDigestsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentSessionDigestsStmt: %w", cerr)
		}
	}
	if q.listReferentCalibrationEpisodesStmt != nil {
		if cerr := q.listReferentCalibrationEpisodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReferentCalibrationEpisodesStmt: %w", cerr)
		}
	}
	if q.listReferentPriorEventsStmt != nil {
		if cerr := q.listReferentPriorEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReferentPriorEventsStmt: %w", cerr)
		}
	}
	if q.listReferentRateEventsStmt != nil {
		if cerr := q.listReferentRateEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReferentRateEventsStmt: %w", cerr)
		}
	}
	if q.listReferentsForPhrasesStmt != nil {
		if cerr := q.listReferentsForPhrasesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReferentsForPhrasesStmt: %w", cerr)
		}
	}
	if q.listResolvedFailuresStmt != nil {
		if cerr := q.listResolvedFailuresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listResolvedFailuresStmt: %w", cerr)
		}
	}
	if q.listSessionCountersStmt != nil {
		if cerr := q.listSessionCountersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionCountersStmt: %w", cerr)
		}
	}
	if q.listSessionOpenFailuresStmt != nil {
		if cerr := q.listSessionOpenFailuresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionOpenFailuresStmt: %w", cerr)
		}
	}
	if q.listSessionReadFilesStmt != nil {
		if cerr := q.listSessionReadFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionReadFilesStmt: %w", cerr)
		}
	}
	if q.listSessionTestVerdictsStmt != nil {
		if cerr := q.listSessionTestVerdictsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionTestVerdictsStmt: %w", cerr)
		}
	}
	if q.listSessionTouchedPathsStmt != nil {
		if cerr := q.listSessionTouchedPathsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionTouchedPathsStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listStaleDigestSessionsStmt != nil {
		if cerr := q.listStaleDigestSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStaleDigestSessionsStmt: %w", cerr)
		}
	}
	if q.listUnclaimedFailuresStmt != nil {
		if cerr := q.listUnclaimedFailuresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUnclaimedFailuresStmt: %w", cerr)
		}
	}
	if q.listUserMessagesBySessionStmt != nil {
		if cerr := q.listUserMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.markReferentEventsFoldedStmt != nil {
		if cerr := q.markReferentEventsFoldedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markReferentEventsFoldedStmt: %w", cerr)
		}
	}
	if q.markSegmentProcessedStmt != nil {
		if cerr := q.markSegmentProcessedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markSegmentProcessedStmt: %w", cerr)
		}
	}
	if q.mergeFailureFirstSeenStmt != nil {
		if cerr := q.mergeFailureFirstSeenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing mergeFailureFirstSeenStmt: %w", cerr)
		}
	}
	if q.promoteReferentStmt != nil {
		if cerr := q.promoteReferentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing promoteReferentStmt: %w", cerr)
		}
	}
	if q.recordCollapsedTurnStmt != nil {
		if cerr := q.recordCollapsedTurnStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordCollapsedTurnStmt: %w", cerr)
		}
	}
	if q.recordFileReadStmt != nil {
		if cerr := q.recordFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordFileReadStmt: %w", cerr)
		}
	}
	if q.recordProcessedSegmentStmt != nil {
		if cerr := q.recordProcessedSegmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordProcessedSegmentStmt: %w", cerr)
		}
	}
	if q.recordSegmentAttemptStmt != nil {
		if cerr := q.recordSegmentAttemptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordSegmentAttemptStmt: %w", cerr)
		}
	}
	if q.rekeyCommandPartitionStmt != nil {
		if cerr := q.rekeyCommandPartitionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing rekeyCommandPartitionStmt: %w", cerr)
		}
	}
	if q.rekeyFailurePartitionStmt != nil {
		if cerr := q.rekeyFailurePartitionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing rekeyFailurePartitionStmt: %w", cerr)
		}
	}
	if q.renameSessionStmt != nil {
		if cerr := q.renameSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing renameSessionStmt: %w", cerr)
		}
	}
	if q.resolveFailuresForCommandStmt != nil {
		if cerr := q.resolveFailuresForCommandStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveFailuresForCommandStmt: %w", cerr)
		}
	}
	if q.searchNotebookByTagStmt != nil {
		if cerr := q.searchNotebookByTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchNotebookByTagStmt: %w", cerr)
		}
	}
	if q.searchNotebookByTextStmt != nil {
		if cerr := q.searchNotebookByTextStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchNotebookByTextStmt: %w", cerr)
		}
	}
	if q.searchSessionDigestsStmt != nil {
		if cerr := q.searchSessionDigestsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchSessionDigestsStmt: %w", cerr)
		}
	}
	if q.setSessionChannelStmt != nil {
		if cerr := q.setSessionChannelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setSessionChannelStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateNotebookCompressionStmt != nil {
		if cerr := q.updateNotebookCompressionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateNotebookCompressionStmt: %w", cerr)
		}
	}
	if q.updateReferentEpisodeLabelStmt != nil {
		if cerr := q.updateReferentEpisodeLabelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateReferentEpisodeLabelStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateSessionTitleAndUsageStmt != nil {
		if cerr := q.updateSessionTitleAndUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionTitleAndUsageStmt: %w", cerr)
		}
	}
	if q.upsertCommandRunStmt != nil {
		if cerr := q.upsertCommandRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertCommandRunStmt: %w", cerr)
		}
	}
	if q.upsertFailureStmt != nil {
		if cerr := q.upsertFailureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertFailureStmt: %w", cerr)
		}
	}
	if q.upsertProjectRateStmt != nil {
		if cerr := q.upsertProjectRateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertProjectRateStmt: %w", cerr)
		}
	}
	if q.upsertSessionDigestStmt != nil {
		if cerr := q.upsertSessionDigestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSessionDigestStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                   DBTX
	tx                                   *sql.Tx
	bumpSessionCounterStmt               *sql.Stmt
	countCleanReferentAcceptancesStmt    *sql.Stmt
	countUserMessagesBySessionStmt       *sql.Stmt
	createFileStmt                       *sql.Stmt
	createMessageStmt                    *sql.Stmt
	createNotebookEntryStmt              *sql.Stmt
	createNotebookTagStmt                *sql.Stmt
	createSessionStmt                    *sql.Stmt
	deleteCommandConflictsStmt           *sql.Stmt
	deleteFailureStmt                    *sql.Stmt
	deleteFileStmt                       *sql.Stmt
	deleteMCPDisabledServerStmt          *sql.Stmt
	deleteMCPEnabledServerStmt           *sql.Stmt
	deleteMessageStmt                    *sql.Stmt
	deleteNotebookEntriesBySessionStmt   *sql.Stmt
	deleteProcessedSegmentsBySessionStmt *sql.Stmt
	deleteSessionStmt                    *sql.Stmt
	deleteSessionDigestStmt              *sql.Stmt
	deleteSessionDigestIndexStmt         *sql.Stmt
	deleteSessionFilesStmt               *sql.Stmt
	deleteSessionMessagesStmt            *sql.Stmt
	getAverageResponseTimeStmt           *sql.Stmt
	getCollapsedTurnStatsStmt            *sql.Stmt
	getEdgeFiringStatsStmt               *sql.Stmt
	getFailureMetaStmt                   *sql.Stmt
	getFileStmt                          *sql.Stmt
	getFileByPathAndSessionStmt          *sql.Stmt
	getFileReadStmt                      *sql.Stmt
	getHourDayHeatmapStmt                *sql.Stmt
	getLastAssistantMessageBySessionStmt *sql.Stmt
	getLastSessionStmt                   *sql.Stmt
	getLatestCheckpointEntryStmt         *sql.Stmt
	getMapUsageStmt                      *sql.Stmt
	getMaxNotebookEventNumberStmt        *sql.Stmt
	getMessageStmt                       *sql.Stmt
	getNotebookEntriesStmt               *sql.Stmt
	getNotebookEntriesByEventTypeStmt    *sql.Stmt
	getNotebookEntriesByTurnStmt         *sql.Stmt
	getNotebookEntriesByTurnSegmentStmt  *sql.Stmt
	getNotebookEntryCountStmt            *sql.Stmt
	getNotebookTagsByEntryStmt           *sql.Stmt
	getNotebookTokenCountStmt            *sql.Stmt
	getNotebookTurnsWithEntriesStmt      *sql.Stmt
	getOldestNotebookEntriesStmt         *sql.Stmt
	getProcessedSegmentStmt              *sql.Stmt
	getProjectRateStmt                   *sql.Stmt
	getPruningStatsStmt                  *sql.Stmt
	getRecentActivityStmt                *sql.Stmt
	getSessionByIDStmt                   *sql.Stmt
	getSessionCounterStmt                *sql.Stmt
	getSessionDigestStmt                 *sql.Stmt
	getToolUsageStmt                     *sql.Stmt
	getTotalStatsStmt                    *sql.Stmt
	getUsageByDayStmt                    *sql.Stmt
	getUsageByDayOfWeekStmt              *sql.Stmt
	getUsageByHourStmt                   *sql.Stmt
	getUsageByModelStmt                  *sql.Stmt
	indexSessionDigestStmt               *sql.Stmt
	insertEdgeFiringStmt                 *sql.Stmt
	insertMCPDisabledServerStmt          *sql.Stmt
	insertMCPEnabledServerStmt           *sql.Stmt
	insertReferentEpisodeStmt            *sql.Stmt
	labelReferentEpisodeStmt             *sql.Stmt
	listAllUserMessagesStmt              *sql.Stmt
	listCommandPartitionKeysStmt         *sql.Stmt
	listFailurePartitionKeysStmt         *sql.Stmt
	listFailuresByKeyStmt                *sql.Stmt
	listFilesByPathStmt                  *sql.Stmt
	listFilesBySessionStmt               *sql.Stmt
	listHotReadFilesStmt                 *sql.Stmt
	listLatestSessionFilesStmt           *sql.Stmt
	listMCPDisabledServersStmt           *sql.Stmt
	listMCPEnabledServersStmt            *sql.Stmt
	listMessagesBySessionStmt            *sql.Stmt
	listMessagesBySessionFromSummaryStmt *sql.Stmt
	listNewFilesStmt                     *sql.Stmt
	listOpenFailuresStmt                 *sql.Stmt
	listPendingReferentLabelsStmt        *sql.Stmt
	listProcessedSegmentsStmt            *sql.Stmt
	listRecentCommandsStmt               *sql.Stmt
	listRecentSessionDigestsStmt         *sql.Stmt
	listReferentCalibrationEpisodesStmt  *sql.Stmt
	listReferentPriorEventsStmt          *sql.Stmt
	listReferentRateEventsStmt           *sql.Stmt
	listReferentsForPhrasesStmt          *sql.Stmt
	listResolvedFailuresStmt             *sql.Stmt
	listSessionCountersStmt              *sql.Stmt
	listSessionOpenFailuresStmt          *sql.Stmt
	listSessionReadFilesStmt             *sql.Stmt
	listSessionTestVerdictsStmt          *sql.Stmt
	listSessionTouchedPathsStmt          *sql.Stmt
	listSessionsStmt                     *sql.Stmt
	listStaleDigestSessionsStmt          *sql.Stmt
	listUnclaimedFailuresStmt            *sql.Stmt
	listUserMessagesBySessionStmt        *sql.Stmt
	markReferentEventsFoldedStmt         *sql.Stmt
	markSegmentProcessedStmt             *sql.Stmt
	mergeFailureFirstSeenStmt            *sql.Stmt
	promoteReferentStmt                  *sql.Stmt
	recordCollapsedTurnStmt              *sql.Stmt
	recordFileReadStmt                   *sql.Stmt
	recordProcessedSegmentStmt           *sql.Stmt
	recordSegmentAttemptStmt             *sql.Stmt
	rekeyCommandPartitionStmt            *sql.Stmt
	rekeyFailurePartitionStmt            *sql.Stmt
	renameSessionStmt                    *sql.Stmt
	resolveFailuresForCommandStmt        *sql.Stmt
	searchNotebookByTagStmt              *sql.Stmt
	searchNotebookByTextStmt             *sql.Stmt
	searchSessionDigestsStmt             *sql.Stmt
	setSessionChannelStmt                *sql.Stmt
	updateMessageStmt                    *sql.Stmt
	updateNotebookCompressionStmt        *sql.Stmt
	updateReferentEpisodeLabelStmt       *sql.Stmt
	updateSessionStmt                    *sql.Stmt
	updateSessionTitleAndUsageStmt       *sql.Stmt
	upsertCommandRunStmt                 *sql.Stmt
	upsertFailureStmt                    *sql.Stmt
	upsertProjectRateStmt                *sql.Stmt
	upsertSessionDigestStmt              *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                   tx,
		tx:                                   tx,
		bumpSessionCounterStmt:               q.bumpSessionCounterStmt,
		countCleanReferentAcceptancesStmt:    q.countCleanReferentAcceptancesStmt,
		countUserMessagesBySessionStmt:       q.countUserMessagesBySessionStmt,
		createFileStmt:                       q.createFileStmt,
		createMessageStmt:                    q.createMessageStmt,
		createNotebookEntryStmt:              q.createNotebookEntryStmt,
		createNotebookTagStmt:                q.createNotebookTagStmt,
		createSessionStmt:                    q.createSessionStmt,
		deleteCommandConflictsStmt:           q.deleteCommandConflictsStmt,
		deleteFailureStmt:                    q.deleteFailureStmt,
		deleteFileStmt:                       q.deleteFileStmt,
		deleteMCPDisabledServerStmt:          q.deleteMCPDisabledServerStmt,
		deleteMCPEnabledServerStmt:           q.deleteMCPEnabledServerStmt,
		deleteMessageStmt:                    q.deleteMessageStmt,
		deleteNotebookEntriesBySessionStmt:   q.deleteNotebookEntriesBySessionStmt,
		deleteProcessedSegmentsBySessionStmt: q.deleteProcessedSegmentsBySessionStmt,
		deleteSessionStmt:                    q.deleteSessionStmt,
		deleteSessionDigestStmt:              q.deleteSessionDigestStmt,
		deleteSessionDigestIndexStmt:         q.deleteSessionDigestIndexStmt,
		deleteSessionFilesStmt:               q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:            q.deleteSessionMessagesStmt,
		getAverageResponseTimeStmt:           q.getAverageResponseTimeStmt,
		getCollapsedTurnStatsStmt:            q.getCollapsedTurnStatsStmt,
		getEdgeFiringStatsStmt:               q.getEdgeFiringStatsStmt,
		getFailureMetaStmt:                   q.getFailureMetaStmt,
		getFileStmt:                          q.getFileStmt,
		getFileByPathAndSessionStmt:          q.getFileByPathAndSessionStmt,
		getFileReadStmt:                      q.getFileReadStmt,
		getHourDayHeatmapStmt:                q.getHourDayHeatmapStmt,
		getLastAssistantMessageBySessionStmt: q.getLastAssistantMessageBySessionStmt,
		getLastSessionStmt:                   q.getLastSessionStmt,
		getLatestCheckpointEntryStmt:         q.getLatestCheckpointEntryStmt,
		getMapUsageStmt:                      q.getMapUsageStmt,
		getMaxNotebookEventNumberStmt:        q.getMaxNotebookEventNumberStmt,
		getMessageStmt:                       q.getMessageStmt,
		getNotebookEntriesStmt:               q.getNotebookEntriesStmt,
		getNotebookEntriesByEventTypeStmt:    q.getNotebookEntriesByEventTypeStmt,
		getNotebookEntriesByTurnStmt:         q.getNotebookEntriesByTurnStmt,
		getNotebookEntriesByTurnSegmentStmt:  q.getNotebookEntriesByTurnSegmentStmt,
		getNotebookEntryCountStmt:            q.getNotebookEntryCountStmt,
		getNotebookTagsByEntryStmt:           q.getNotebookTagsByEntryStmt,
		getNotebookTokenCountStmt:            q.getNotebookTokenCountStmt,
		getNotebookTurnsWithEntriesStmt:      q.getNotebookTurnsWithEntriesStmt,
		getOldestNotebookEntriesStmt:         q.getOldestNotebookEntriesStmt,
		getProcessedSegmentStmt:              q.getProcessedSegmentStmt,
		getProjectRateStmt:                   q.getProjectRateStmt,
		getPruningStatsStmt:                  q.getPruningStatsStmt,
		getRecentActivityStmt:                q.getRecentActivityStmt,
		getSessionByIDStmt:                   q.getSessionByIDStmt,
		getSessionCounterStmt:                q.getSessionCounterStmt,
		getSessionDigestStmt:                 q.getSessionDigestStmt,
		getToolUsageStmt:                     q.getToolUsageStmt,
		getTotalStatsStmt:                    q.getTotalStatsStmt,
		getUsageByDayStmt:                    q.getUsageByDayStmt,
		getUsageByDayOfWeekStmt:              q.getUsageByDayOfWeekStmt,
		getUsageByHourStmt:                   q.getUsageByHourStmt,
		getUsageByModelStmt:                  q.getUsageByModelStmt,
		indexSessionDigestStmt:               q.indexSessionDigestStmt,
		insertEdgeFiringStmt:                 q.insertEdgeFiringStmt,
		insertMCPDisabledServerStmt:          q.insertMCPDisabledServerStmt,
		insertMCPEnabledServerStmt:           q.insertMCPEnabledServerStmt,
		insertReferentEpisodeStmt:            q.insertReferentEpisodeStmt,
		labelReferentEpisodeStmt:             q.labelReferentEpisodeStmt,
		listAllUserMessagesStmt:              q.listAllUserMessagesStmt,
		listCommandPartitionKeysStmt:         q.listCommandPartitionKeysStmt,
		listFailurePartitionKeysStmt:         q.listFailurePartitionKeysStmt,
		listFailuresByKeyStmt:                q.listFailuresByKeyStmt,
		listFilesByPathStmt:                  q.listFilesByPathStmt,
		listFilesBySessionStmt:               q.listFilesBySessionStmt,
		listHotReadFilesStmt:                 q.listHotReadFilesStmt,
		listLatestSessionFilesStmt:           q.listLatestSessionFilesStmt,
		listMCPDisabledServersStmt:           q.listMCPDisabledServersStmt,
		listMCPEnabledServersStmt:            q.listMCPEnabledServersStmt,
		listMessagesBySessionStmt:            q.listMessagesBySessionStmt,
		listMessagesBySessionFromSummaryStmt: q.listMessagesBySessionFromSummaryStmt,
		listNewFilesStmt:                     q.listNewFilesStmt,
		listOpenFailuresStmt:                 q.listOpenFailuresStmt,
		listPendingReferentLabelsStmt:        q.listPendingReferentLabelsStmt,
		listProcessedSegmentsStmt:            q.listProcessedSegmentsStmt,
		listRecentCommandsStmt:               q.listRecentCommandsStmt,
		listRecentSessionDigestsStmt:         q.listRecentSessionDigestsStmt,
		listReferentCalibrationEpisodesStmt:  q.listReferentCalibrationEpisodesStmt,
		listReferentPriorEventsStmt:          q.listReferentPriorEventsStmt,
		listReferentRateEventsStmt:           q.listReferentRateEventsStmt,
		listReferentsForPhrasesStmt:          q.listReferentsForPhrasesStmt,
		listResolvedFailuresStmt:             q.listResolvedFailuresStmt,
		listSessionCountersStmt:              q.listSessionCountersStmt,
		listSessionOpenFailuresStmt:          q.listSessionOpenFailuresStmt,
		listSessionReadFilesStmt:             q.listSessionReadFilesStmt,
		listSessionTestVerdictsStmt:          q.listSessionTestVerdictsStmt,
		listSessionTouchedPathsStmt:          q.listSessionTouchedPathsStmt,
		listSessionsStmt:                     q.listSessionsStmt,
		listStaleDigestSessionsStmt:          q.listStaleDigestSessionsStmt,
		listUnclaimedFailuresStmt:            q.listUnclaimedFailuresStmt,
		listUserMessagesBySessionStmt:        q.listUserMessagesBySessionStmt,
		markReferentEventsFoldedStmt:         q.markReferentEventsFoldedStmt,
		markSegmentProcessedStmt:             q.markSegmentProcessedStmt,
		mergeFailureFirstSeenStmt:            q.mergeFailureFirstSeenStmt,
		promoteReferentStmt:                  q.promoteReferentStmt,
		recordCollapsedTurnStmt:              q.recordCollapsedTurnStmt,
		recordFileReadStmt:                   q.recordFileReadStmt,
		recordProcessedSegmentStmt:           q.recordProcessedSegmentStmt,
		recordSegmentAttemptStmt:             q.recordSegmentAttemptStmt,
		rekeyCommandPartitionStmt:            q.rekeyCommandPartitionStmt,
		rekeyFailurePartitionStmt:            q.rekeyFailurePartitionStmt,
		renameSessionStmt:                    q.renameSessionStmt,
		resolveFailuresForCommandStmt:        q.resolveFailuresForCommandStmt,
		searchNotebookByTagStmt:              q.searchNotebookByTagStmt,
		searchNotebookByTextStmt:             q.searchNotebookByTextStmt,
		searchSessionDigestsStmt:             q.searchSessionDigestsStmt,
		setSessionChannelStmt:                q.setSessionChannelStmt,
		updateMessageStmt:                    q.updateMessageStmt,
		updateNotebookCompressionStmt:        q.updateNotebookCompressionStmt,
		updateReferentEpisodeLabelStmt:       q.updateReferentEpisodeLabelStmt,
		updateSessionStmt:                    q.updateSessionStmt,
		updateSessionTitleAndUsageStmt:       q.updateSessionTitleAndUsageStmt,
		upsertCommandRunStmt:                 q.upsertCommandRunStmt,
		upsertFailureStmt:                    q.upsertFailureStmt,
		upsertProjectRateStmt:                q.upsertProjectRateStmt,
		upsertSessionDigestStmt:              q.upsertSessionDigestStmt,
	}
}
