// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: digests.sql

package db

import (
	"context"
)

const deleteSessionDigest = `-- name: DeleteSessionDigest :exec
DELETE FROM session_digests WHERE session_id = ?
`

func (q *Queries) DeleteSessionDigest(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionDigestStmt, deleteSessionDigest, sessionID)
	return err
}

const deleteSessionDigestIndex = `-- name: DeleteSessionDigestIndex :exec
DELETE FROM session_digests_fts WHERE session_id = ?
`

func (q *Queries) DeleteSessionDigestIndex(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionDigestIndexStmt, deleteSessionDigestIndex, sessionID)
	return err
}

const getLatestCheckpointEntry = `-- name: GetLatestCheckpointEntry :one

SELECT e.title, e.entry_text FROM notebook_entries e
LEFT JOIN notebook_tags t ON t.entry_id = e.id
    AND t.tag LIKE 'granularity:%'
WHERE e.session_id = ? AND e.event_type = 'checkpoint'
ORDER BY
    CASE t.tag
        WHEN 'granularity:turn' THEN 0
        WHEN 'granularity:boundary' THEN 1
        WHEN 'granularity:session' THEN 2
        ELSE 3
    END DESC,
    e.turn_number DESC,
    e.event_number DESC
LIMIT 1
`

type GetLatestCheckpointEntryRow struct {
	Title     string `json:"title"`
	EntryText string `json:"entry_text"`
}

// Session digests (#164): one resumable row per session + an FTS5
// shadow for paraphrased cross-session retrieval. Pointers only ---
// titles, paths, dates.
//
// FTS5 notes: sqlc catalogs the virtual table's columns but cannot
// resolve `session_digests_fts MATCH` (table-name MATCH), so queries
// use `body MATCH` --- equivalent here since body is the only indexed
// column. Explicit column lists everywhere: sqlc's `*` expansion
// re-parses badly against this schema.
// The session's consolidated position --- the digest's narrative
// field where the notebook produced one. Coarsest granularity wins
// before recency: a session- or boundary-grain checkpoint carries the
// whole position, so a turn-grain one written later must not displace
// it. Untagged checkpoints rank coarsest, matching granularityRank.
func (q *Queries) GetLatestCheckpointEntry(ctx context.Context, sessionID string) (GetLatestCheckpointEntryRow, error) {
	row := q.queryRow(ctx, q.getLatestCheckpointEntryStmt, getLatestCheckpointEntry, sessionID)
	var i GetLatestCheckpointEntryRow
	err := row.Scan(&i.Title, &i.EntryText)
	return i, err
}

const getSessionDigest = `-- name: GetSessionDigest :one
SELECT session_id, title, checkpoint, files, ended_at, project_key,
       param_version
FROM session_digests
WHERE session_id = ? LIMIT 1
`

func (q *Queries) GetSessionDigest(ctx context.Context, sessionID string) (SessionDigest, error) {
	row := q.queryRow(ctx, q.getSessionDigestStmt, getSessionDigest, sessionID)
	var i SessionDigest
	err := row.Scan(
		&i.SessionID,
		&i.Title,
		&i.Checkpoint,
		&i.Files,
		&i.EndedAt,
		&i.ProjectKey,
		&i.ParamVersion,
	)
	return i, err
}

const indexSessionDigest = `-- name: IndexSessionDigest :exec
INSERT INTO session_digests_fts (session_id, body) VALUES (?, ?)
`

type IndexSessionDigestParams struct {
	SessionID string `json:"session_id"`
	Body      string `json:"body"`
}

// The FTS shadow is a plain FTS5 table (not external-content) so a
// digest refresh is a keyed delete + insert.
func (q *Queries) IndexSessionDigest(ctx context.Context, arg IndexSessionDigestParams) error {
	_, err := q.exec(ctx, q.indexSessionDigestStmt, indexSessionDigest, arg.SessionID, arg.Body)
	return err
}

const listRecentSessionDigests = `-- name: ListRecentSessionDigests :many
SELECT session_id, title, checkpoint, files, ended_at, project_key,
       param_version
FROM session_digests
WHERE project_key = ? AND session_id != ?
ORDER BY ended_at DESC
LIMIT ?
`

type ListRecentSessionDigestsParams struct {
	ProjectKey string `json:"project_key"`
	SessionID  string `json:"session_id"`
	Limit      int64  `json:"limit"`
}

// The recency fallback: "continue" carries no terms to match, so the
// tail offers the freshest other sessions instead.
func (q *Queries) ListRecentSessionDigests(ctx context.Context, arg ListRecentSessionDigestsParams) ([]SessionDigest, error) {
	rows, err := q.query(ctx, q.listRecentSessionDigestsStmt, listRecentSessionDigests, arg.ProjectKey, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionDigest{}
	for rows.Next() {
		var i SessionDigest
		if err := rows.Scan(
			&i.SessionID,
			&i.Title,
			&i.Checkpoint,
			&i.Files,
			&i.EndedAt,
			&i.ProjectKey,
			&i.ParamVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTouchedPaths = `-- name: ListSessionTouchedPaths :many
SELECT DISTINCT path FROM read_files WHERE read_files.session_id = ?
UNION
SELECT DISTINCT path FROM files WHERE files.session_id = ?
ORDER BY path
`

type ListSessionTouchedPathsParams struct {
	SessionID   string `json:"session_id"`
	SessionID_2 string `json:"session_id_2"`
}

// Read files are already workspace-relative; files rows store the
// path the tool passed, relativized service-side when needed.
func (q *Queries) ListSessionTouchedPaths(ctx context.Context, arg ListSessionTouchedPathsParams) ([]string, error) {
	rows, err := q.query(ctx, q.listSessionTouchedPathsStmt, listSessionTouchedPaths, arg.SessionID, arg.SessionID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleDigestSessions = `-- name: ListStaleDigestSessions :many
SELECT s.id, s.title, s.updated_at
FROM sessions s
LEFT JOIN session_digests d ON d.session_id = s.id
WHERE s.parent_session_id IS NULL
  AND (d.session_id IS NULL OR s.updated_at > d.ended_at)
ORDER BY s.updated_at DESC
LIMIT ?
`

type ListStaleDigestSessionsRow struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	UpdatedAt int64  `json:"updated_at"`
}

// Sessions whose digest is missing or older than their last update ---
// the lazy-refresh worklist. Sub-agent sessions (parent_session_id
// set) are internal machinery, not user work, so they stay out.
func (q *Queries) ListStaleDigestSessions(ctx context.Context, limit int64) ([]ListStaleDigestSessionsRow, error) {
	rows, err := q.query(ctx, q.listStaleDigestSessionsStmt, listStaleDigestSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleDigestSessionsRow{}
	for rows.Next() {
		var i ListStaleDigestSessionsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSessionDigests = `-- name: SearchSessionDigests :many
SELECT d.session_id, d.title, d.checkpoint, d.files, d.ended_at,
       d.project_key, d.param_version
FROM session_digests_fts f
JOIN session_digests d ON d.session_id = f.session_id
WHERE f.body MATCH ? AND d.project_key = ? AND d.session_id != ?
ORDER BY f.rank LIMIT ?
`

type SearchSessionDigestsParams struct {
	Body       string `json:"body"`
	ProjectKey string `json:"project_key"`
	SessionID  string `json:"session_id"`
	Limit      int64  `json:"limit"`
}

// FTS5 match on the digest body (title + checkpoint + files) joined
// back to the pointer fields. `body MATCH` --- not
// `session_digests_fts MATCH` --- because sqlc resolves column MATCH
// but not table-name MATCH; body is the only indexed column so the
// two are equivalent here.
func (q *Queries) SearchSessionDigests(ctx context.Context, arg SearchSessionDigestsParams) ([]SessionDigest, error) {
	rows, err := q.query(ctx, q.searchSessionDigestsStmt, searchSessionDigests,
		arg.Body,
		arg.ProjectKey,
		arg.SessionID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionDigest{}
	for rows.Next() {
		var i SessionDigest
		if err := rows.Scan(
			&i.SessionID,
			&i.Title,
			&i.Checkpoint,
			&i.Files,
			&i.EndedAt,
			&i.ProjectKey,
			&i.ParamVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSessionDigest = `-- name: UpsertSessionDigest :exec
INSERT INTO session_digests (
    session_id, title, checkpoint, files, ended_at, project_key,
    param_version
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (session_id) DO UPDATE SET
    title = excluded.title,
    checkpoint = excluded.checkpoint,
    files = excluded.files,
    ended_at = excluded.ended_at,
    project_key = excluded.project_key,
    param_version = excluded.param_version
`

type UpsertSessionDigestParams struct {
	SessionID    string `json:"session_id"`
	Title        string `json:"title"`
	Checkpoint   string `json:"checkpoint"`
	Files        string `json:"files"`
	EndedAt      int64  `json:"ended_at"`
	ProjectKey   string `json:"project_key"`
	ParamVersion string `json:"param_version"`
}

// The digest is a per-turn refresh of the session's resumable view:
// title + latest checkpoint + touched files. ended_at follows the
// session row's updated_at --- the closest thing to an end timestamp a
// session has (sessions never formally end).
func (q *Queries) UpsertSessionDigest(ctx context.Context, arg UpsertSessionDigestParams) error {
	_, err := q.exec(ctx, q.upsertSessionDigestStmt, upsertSessionDigest,
		arg.SessionID,
		arg.Title,
		arg.Checkpoint,
		arg.Files,
		arg.EndedAt,
		arg.ProjectKey,
		arg.ParamVersion,
	)
	return err
}
