// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edge_firings.sql

package db

import (
	"context"
)

const getEdgeFiringStats = `-- name: GetEdgeFiringStats :many
SELECT
    edge,
    outcome,
    COUNT(*) AS firings,
    COUNT(DISTINCT session_id) AS sessions
FROM edge_firings
GROUP BY edge, outcome
ORDER BY edge, outcome
`

type GetEdgeFiringStatsRow struct {
	Edge     string `json:"edge"`
	Outcome  string `json:"outcome"`
	Firings  int64  `json:"firings"`
	Sessions int64  `json:"sessions"`
}

func (q *Queries) GetEdgeFiringStats(ctx context.Context) ([]GetEdgeFiringStatsRow, error) {
	rows, err := q.query(ctx, q.getEdgeFiringStatsStmt, getEdgeFiringStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEdgeFiringStatsRow{}
	for rows.Next() {
		var i GetEdgeFiringStatsRow
		if err := rows.Scan(
			&i.Edge,
			&i.Outcome,
			&i.Firings,
			&i.Sessions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEdgeFiring = `-- name: InsertEdgeFiring :execrows
INSERT OR IGNORE INTO edge_firings (
    session_id,
    turn_seq,
    edge,
    variant,
    repair_attempts,
    trigger_detail,
    outcome,
    run_stamp,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now')
)
`

type InsertEdgeFiringParams struct {
	SessionID      string `json:"session_id"`
	TurnSeq        int64  `json:"turn_seq"`
	Edge           string `json:"edge"`
	Variant        string `json:"variant"`
	RepairAttempts int64  `json:"repair_attempts"`
	TriggerDetail  string `json:"trigger_detail"`
	Outcome        string `json:"outcome"`
	RunStamp       int64  `json:"run_stamp"`
}

// One row per edge per run boundary; INSERT OR IGNORE makes the write
// idempotent within a boundary, so callers count a firing only when
// this reports a new row.
func (q *Queries) InsertEdgeFiring(ctx context.Context, arg InsertEdgeFiringParams) (int64, error) {
	result, err := q.exec(ctx, q.insertEdgeFiringStmt, insertEdgeFiring,
		arg.SessionID,
		arg.TurnSeq,
		arg.Edge,
		arg.Variant,
		arg.RepairAttempts,
		arg.TriggerDetail,
		arg.Outcome,
		arg.RunStamp,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
