// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type CollapsedTurn struct {
	SessionID  string `json:"session_id"`
	TurnNumber int64  `json:"turn_number"`
	Events     int64  `json:"events"`
	CreatedAt  int64  `json:"created_at"`
}

type CommandMemory struct {
	CmdNorm        string `json:"cmd_norm"`
	Cwd            string `json:"cwd"`
	Kind           string `json:"kind"`
	LastExit       int64  `json:"last_exit"`
	LastAt         int64  `json:"last_at"`
	OkCount        int64  `json:"ok_count"`
	FailCount      int64  `json:"fail_count"`
	LastSessionID  string `json:"last_session_id"`
	LastToolCallID string `json:"last_tool_call_id"`
	RepoState      string `json:"repo_state"`
	Suggested      int64  `json:"suggested"`
	ProjectKey     string `json:"project_key"`
	ParamVersion   string `json:"param_version"`
}

type EdgeFiring struct {
	SessionID      string `json:"session_id"`
	TurnSeq        int64  `json:"turn_seq"`
	Edge           string `json:"edge"`
	Variant        string `json:"variant"`
	RepairAttempts int64  `json:"repair_attempts"`
	TriggerDetail  string `json:"trigger_detail"`
	Outcome        string `json:"outcome"`
	RunStamp       int64  `json:"run_stamp"`
	CreatedAt      int64  `json:"created_at"`
}

type FailureMemory struct {
	Signature    string `json:"signature"`
	Cmd          string `json:"cmd"`
	Cwd          string `json:"cwd"`
	Headline     string `json:"headline"`
	Files        string `json:"files"`
	FirstSeen    int64  `json:"first_seen"`
	LastSeen     int64  `json:"last_seen"`
	ResolvedIn   string `json:"resolved_in"`
	SessionID    string `json:"session_id"`
	ToolCallID   string `json:"tool_call_id"`
	RepoState    string `json:"repo_state"`
	Suggested    int64  `json:"suggested"`
	ProjectKey   string `json:"project_key"`
	ParamVersion string `json:"param_version"`
	ResolvedCall string `json:"resolved_call"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type McpDisabledServer struct {
	Name string `json:"name"`
}

type McpEnabledServer struct {
	Name string `json:"name"`
}

type Message struct {
	ID                      string          `json:"id"`
	SessionID               string          `json:"session_id"`
	Role                    string          `json:"role"`
	Parts                   string          `json:"parts"`
	Model                   sql.NullString  `json:"model"`
	CreatedAt               int64           `json:"created_at"`
	UpdatedAt               int64           `json:"updated_at"`
	FinishedAt              sql.NullInt64   `json:"finished_at"`
	Provider                sql.NullString  `json:"provider"`
	IsSummaryMessage        int64           `json:"is_summary_message"`
	PrismModelID            sql.NullString  `json:"prism_model_id"`
	PrismModelName          sql.NullString  `json:"prism_model_name"`
	PrismHypercreditSavings sql.NullFloat64 `json:"prism_hypercredit_savings"`
	PrismDollarSavings      sql.NullFloat64 `json:"prism_dollar_savings"`
}

type NotebookEntry struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	TurnNumber       int64          `json:"turn_number"`
	EventNumber      int64          `json:"event_number"`
	EventType        string         `json:"event_type"`
	Title            string         `json:"title"`
	EntryText        string         `json:"entry_text"`
	EntryTextFull    sql.NullString `json:"entry_text_full"`
	TokenCount       int64          `json:"token_count"`
	CompressionLevel int64          `json:"compression_level"`
	CreatedAt        int64          `json:"created_at"`
	Succeeded        int64          `json:"succeeded"`
	ErrorHeadline    string         `json:"error_headline"`
	SegmentNumber    int64          `json:"segment_number"`
	Verified         string         `json:"verified"`
}

type NotebookTag struct {
	EntryID string `json:"entry_id"`
	Tag     string `json:"tag"`
}

type ProcessedSegment struct {
	SessionID     string        `json:"session_id"`
	TurnNumber    int64         `json:"turn_number"`
	SegmentNumber int64         `json:"segment_number"`
	StartIndex    int64         `json:"start_index"`
	EndIndex      int64         `json:"end_index"`
	State         string        `json:"state"`
	RetryCount    int64         `json:"retry_count"`
	LastAttemptAt sql.NullInt64 `json:"last_attempt_at"`
	CreatedAt     int64         `json:"created_at"`
}

type ProjectRate struct {
	ProjectKey    string  `json:"project_key"`
	Signal        string  `json:"signal"`
	Alpha         float64 `json:"alpha"`
	Beta          float64 `json:"beta"`
	LastEventID   int64   `json:"last_event_id"`
	LastSessionID string  `json:"last_session_id"`
	UpdatedAt     int64   `json:"updated_at"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type ReferentEpisode struct {
	ID               int64         `json:"id"`
	Phrase           string        `json:"phrase"`
	Target           string        `json:"target"`
	SessionID        string        `json:"session_id"`
	SourceMessageID  string        `json:"source_message_id"`
	ToolCallID       string        `json:"tool_call_id"`
	RepoState        string        `json:"repo_state"`
	MemorySuggested  int64         `json:"memory_suggested"`
	Verdict          string        `json:"verdict"`
	ProjectKey       string        `json:"project_key"`
	ParamVersion     string        `json:"param_version"`
	CreatedAt        int64         `json:"created_at"`
	LabelTargetHash  string        `json:"label_target_hash"`
	LabelHashChanged sql.NullInt64 `json:"label_hash_changed"`
	LabelCommitted   sql.NullInt64 `json:"label_committed"`
	LabelTestsGreen  sql.NullInt64 `json:"label_tests_green"`
	LabelWrongTarget int64         `json:"label_wrong_target"`
	LabelSteps       int64         `json:"label_steps"`
	LabelTokens      int64         `json:"label_tokens"`
	LabeledAt        int64         `json:"labeled_at"`
	RateFolded       int64         `json:"rate_folded"`
}

type ReferentMemory struct {
	Phrase       string `json:"phrase"`
	Target       string `json:"target"`
	Hits         int64  `json:"hits"`
	LastAt       int64  `json:"last_at"`
	ProjectKey   string `json:"project_key"`
	ParamVersion string `json:"param_version"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Todos            sql.NullString `json:"todos"`
	Channel          sql.NullString `json:"channel"`
}

type SessionCounter struct {
	SessionID string `json:"session_id"`
	Name      string `json:"name"`
	Value     int64  `json:"value"`
}

type SessionDigest struct {
	SessionID    string `json:"session_id"`
	Title        string `json:"title"`
	Checkpoint   string `json:"checkpoint"`
	Files        string `json:"files"`
	EndedAt      int64  `json:"ended_at"`
	ProjectKey   string `json:"project_key"`
	ParamVersion string `json:"param_version"`
}

type SessionDigestsFt struct {
	SessionID string `json:"session_id"`
	Body      string `json:"body"`
}
