// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	BumpSessionCounter(ctx context.Context, arg BumpSessionCounterParams) error
	// Evidence for a phrase->target mapping: accepted episodes the memory
	// tail did not suggest, counted by distinct session so a session
	// re-deriving its own mapping cannot self-promote.
	CountCleanReferentAcceptances(ctx context.Context, arg CountCleanReferentAcceptancesParams) (int64, error)
	// Absolute user-turn ordinal source for edge_firings.turn_seq - the
	// bounded prompt-history query above can't serve it (DESC LIMIT 200
	// yields no ASC ordinal past 200 and same-second created_at ties are
	// ambiguous).
	CountUserMessagesBySession(ctx context.Context, sessionID string) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNotebookEntry(ctx context.Context, arg CreateNotebookEntryParams) (NotebookEntry, error)
	CreateNotebookTag(ctx context.Context, arg CreateNotebookTagParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Re-key collision on command_memory: project_key is PK material, so
	// moving a row from source key to target key conflicts when the
	// (cmd_norm, cwd, target) twin already exists. The target twin wins
	// -- fresher provenance -- so the stale row goes before the re-key.
	DeleteCommandConflicts(ctx context.Context, arg DeleteCommandConflictsParams) error
	DeleteFailure(ctx context.Context, signature string) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMCPDisabledServer(ctx context.Context, name string) error
	DeleteMCPEnabledServer(ctx context.Context, name string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteNotebookEntriesBySession(ctx context.Context, sessionID string) error
	DeleteProcessedSegmentsBySession(ctx context.Context, sessionID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionDigest(ctx context.Context, sessionID string) error
	DeleteSessionDigestIndex(ctx context.Context, sessionID string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetCollapsedTurnStats(ctx context.Context) (GetCollapsedTurnStatsRow, error)
	GetEdgeFiringStats(ctx context.Context) ([]GetEdgeFiringStatsRow, error)
	GetFailureMeta(ctx context.Context, signature string) (GetFailureMetaRow, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastAssistantMessageBySession(ctx context.Context, sessionID string) (Message, error)
	GetLastSession(ctx context.Context) (Session, error)
	// Session digests (#164): one resumable row per session + an FTS5
	// shadow for paraphrased cross-session retrieval. Pointers only ---
	// titles, paths, dates.
	//
	// FTS5 notes: sqlc catalogs the virtual table's columns but cannot
	// resolve `session_digests_fts MATCH` (table-name MATCH), so queries
	// use `body MATCH` --- equivalent here since body is the only indexed
	// column. Explicit column lists everywhere: sqlc's `*` expansion
	// re-parses badly against this schema.
	// The session's consolidated position --- the digest's narrative
	// field where the notebook produced one. Coarsest granularity wins
	// before recency: a session- or boundary-grain checkpoint carries the
	// whole position, so a turn-grain one written later must not displace
	// it. Untagged checkpoints rank coarsest, matching granularityRank.
	GetLatestCheckpointEntry(ctx context.Context, sessionID string) (GetLatestCheckpointEntryRow, error)
	// Per-tool call count plus the number of distinct sessions that used
	// it: the per-session split the GROUP BY aggregate loses. Counts
	// attempted calls (tool-not-found results included), so flag-off
	// reach is measurable.
	GetMapUsage(ctx context.Context) (GetMapUsageRow, error)
	GetMaxNotebookEventNumber(ctx context.Context, arg GetMaxNotebookEventNumberParams) (int64, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetNotebookEntries(ctx context.Context, sessionID string) ([]NotebookEntry, error)
	GetNotebookEntriesByEventType(ctx context.Context, arg GetNotebookEntriesByEventTypeParams) ([]NotebookEntry, error)
	GetNotebookEntriesByTurn(ctx context.Context, arg GetNotebookEntriesByTurnParams) ([]NotebookEntry, error)
	GetNotebookEntriesByTurnSegment(ctx context.Context, arg GetNotebookEntriesByTurnSegmentParams) ([]NotebookEntry, error)
	GetNotebookEntryCount(ctx context.Context, sessionID string) (int64, error)
	GetNotebookTagsByEntry(ctx context.Context, entryID string) ([]string, error)
	GetNotebookTokenCount(ctx context.Context, sessionID string) (int64, error)
	GetNotebookTurnsWithEntries(ctx context.Context, arg GetNotebookTurnsWithEntriesParams) ([]int64, error)
	GetOldestNotebookEntries(ctx context.Context, arg GetOldestNotebookEntriesParams) ([]NotebookEntry, error)
	GetProcessedSegment(ctx context.Context, arg GetProcessedSegmentParams) (ProcessedSegment, error)
	// One row per tool result that renders as a stub (applied superseded
	// mark). content_head carries the first 1024 chars so callers can
	// recompute exact stub text for prefix-bearing stub kinds.
	GetPruningStats(ctx context.Context) ([]GetPruningStatsRow, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSessionCounter(ctx context.Context, arg GetSessionCounterParams) (int64, error)
	GetSessionDigest(ctx context.Context, sessionID string) (SessionDigest, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	// The FTS shadow is a plain FTS5 table (not external-content) so a
	// digest refresh is a keyed delete + insert.
	IndexSessionDigest(ctx context.Context, arg IndexSessionDigestParams) error
	// One row per edge per run boundary; INSERT OR IGNORE makes the write
	// idempotent within a boundary, so callers count a firing only when
	// this reports a new row.
	InsertEdgeFiring(ctx context.Context, arg InsertEdgeFiringParams) (int64, error)
	InsertMCPDisabledServer(ctx context.Context, name string) error
	InsertMCPEnabledServer(ctx context.Context, name string) error
	// One judged vague-prompt observation (#165). INSERT OR IGNORE makes
	// the (session_id, source_message_id, target) unique key the retry
	// idempotency point: a repair-chain re-run of the turn-context pass
	// re-derives the same episode and must not count twice.
	InsertReferentEpisode(ctx context.Context, arg InsertReferentEpisodeParams) error
	// Backs prompt history when no session is open. Needs
	// idx_messages_role_created_at to seek rather than scan the table.
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListCommandPartitionKeys(ctx context.Context) ([]string, error)
	ListFailurePartitionKeys(ctx context.Context) ([]string, error)
	// Failure rows in one partition -- the remote-lifecycle re-claim
	// (#266) moves them off a stale key onto the current one.
	ListFailuresByKey(ctx context.Context, projectKey string) ([]ListFailuresByKeyRow, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	// Project-wide file heat: files prior sessions in this workspace
	// touched, ranked by persistence (how many sessions read the file)
	// then recency. The current session is excluded -- its files are the
	// working set, not heat; a file only this session read would carry
	// a sessions count of 1 noise-signal anyway.
	ListHotReadFiles(ctx context.Context, arg ListHotReadFilesParams) ([]ListHotReadFilesRow, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMCPDisabledServers(ctx context.Context) ([]string, error)
	ListMCPEnabledServers(ctx context.Context) ([]string, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// Messages from the summary onward, which is all a compacted session sends.
	// created_at has one-second resolution, so a few messages preceding the
	// summary can come back too; the caller slices from the summary by ID.
	ListMessagesBySessionFromSummary(ctx context.Context, arg ListMessagesBySessionFromSummaryParams) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListOpenFailures(ctx context.Context, arg ListOpenFailuresParams) ([]FailureMemory, error)
	ListProcessedSegments(ctx context.Context, sessionID string) ([]ProcessedSegment, error)
	// last_at is millisecond-granularity so re-runs order by recency;
	// rowid settles ties for rows written in the same millisecond.
	// project_key is an admissibility clause, not a ranking signal: a
	// candidate from another partition is inadmissible before relevance
	// ever runs.
	ListRecentCommands(ctx context.Context, arg ListRecentCommandsParams) ([]CommandMemory, error)
	// The recency fallback: "continue" carries no terms to match, so the
	// tail offers the freshest other sessions instead.
	ListRecentSessionDigests(ctx context.Context, arg ListRecentSessionDigestsParams) ([]SessionDigest, error)
	// Promoted candidates whose learned phrase appears among the turn's
	// extracted phrases -- exact-match on the normalized phrase keeps the
	// render honest (a fuzzy hit would be a guess, not learned evidence).
	// Bare placeholders only: numbered ?N collides with the slice's
	// variable-length expansion at bind time.
	ListReferentsForPhrases(ctx context.Context, arg ListReferentsForPhrasesParams) ([]ReferentMemory, error)
	// Resolved rows are knowledge, not warnings: the failure signature
	// and when it last saw a clean run. Ordered by last_seen (the last
	// failing observation), not resolution time -- the row's freshness
	// is still about when the failure was last real.
	ListResolvedFailures(ctx context.Context, arg ListResolvedFailuresParams) ([]FailureMemory, error)
	ListSessionCounters(ctx context.Context) ([]ListSessionCountersRow, error)
	// Open failure rows whose commands the given session (or one of its
	// task-tool child sessions) last ran and last failed: the reconcile
	// edge's "observed and left open" set. A sub-agent's bash records
	// under the child session ID; without the children subquery those
	// rows would reconcile to no one -- the child never scans and the
	// parent's delegation produced the mess. One level only, matching
	// the task tool's nesting depth. command_memory's last_session_id
	// is last-writer, so a row another session re-ran more recently
	// drops out of this session's set even while it stays open; a
	// concurrently opened row the run never invoked can never flag here.
	// Same bound as the tail's fetch pool -- a session can observe more
	// distinct commands than this only pathologically, and the retry
	// prompt renders at most ten.
	ListSessionOpenFailures(ctx context.Context, arg ListSessionOpenFailuresParams) ([]FailureMemory, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	// Read files are already workspace-relative; files rows store the
	// path the tool passed, relativized service-side when needed.
	ListSessionTouchedPaths(ctx context.Context, arg ListSessionTouchedPathsParams) ([]string, error)
	ListSessions(ctx context.Context) ([]Session, error)
	// Sessions whose digest is missing or older than their last update ---
	// the lazy-refresh worklist. Sub-agent sessions (parent_session_id
	// set) are internal machinery, not user work, so they stay out.
	ListStaleDigestSessions(ctx context.Context, limit int64) ([]ListStaleDigestSessionsRow, error)
	// Legacy failure rows awaiting a partition claim (pre-provenance
	// writes). The claim re-keys them Go-side because the signature hash
	// itself carries project_key -- a column UPDATE alone would leave a
	// stale PK, and the next occurrence of the same failure would open a
	// second row.
	ListUnclaimedFailures(ctx context.Context) ([]ListUnclaimedFailuresRow, error)
	// Backs prompt history, which steps back one entry at a time.
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	MarkSegmentProcessed(ctx context.Context, arg MarkSegmentProcessedParams) error
	// A claimed row colliding with an already-partitioned twin keeps the
	// twin (fresher provenance) but the failure's true age survives --
	// the caller passes min(twin.first_seen, legacy.first_seen).
	MergeFailureFirstSeen(ctx context.Context, arg MergeFailureFirstSeenParams) error
	// A mapping that cleared the acceptance floor earns its row; further
	// clean acceptances keep scoring it (hits is evidence mass, not
	// capped at the threshold).
	PromoteReferent(ctx context.Context, arg PromoteReferentParams) error
	// One row per collapsed prior turn; INSERT OR IGNORE makes the write
	// idempotent across renders and across processes sharing the session
	// DB, so callers count a turn only when this reports a new row.
	RecordCollapsedTurn(ctx context.Context, arg RecordCollapsedTurnParams) (int64, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RecordProcessedSegment(ctx context.Context, arg RecordProcessedSegmentParams) error
	RecordSegmentAttempt(ctx context.Context, arg RecordSegmentAttemptParams) error
	RekeyCommandPartition(ctx context.Context, arg RekeyCommandPartitionParams) error
	// Claim one legacy row onto its partitioned signature.
	RekeyFailurePartition(ctx context.Context, arg RekeyFailurePartitionParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	// A clean run of a normalized command resolves its open failure rows
	// in the same directory -- "go test ./..." passing in packages/web
	// does not close packages/api's failure. resolved_call names the
	// call that carried the clean verdict, where detectable. The
	// resolution is partition-scoped like every read: one project's
	// green run cannot close another's observation.
	ResolveFailuresForCommand(ctx context.Context, arg ResolveFailuresForCommandParams) error
	SearchNotebookByTag(ctx context.Context, arg SearchNotebookByTagParams) ([]NotebookEntry, error)
	SearchNotebookByText(ctx context.Context, arg SearchNotebookByTextParams) ([]NotebookEntry, error)
	// FTS5 match on the digest body (title + checkpoint + files) joined
	// back to the pointer fields. `body MATCH` --- not
	// `session_digests_fts MATCH` --- because sqlc resolves column MATCH
	// but not table-name MATCH; body is the only indexed column so the
	// two are equivalent here.
	SearchSessionDigests(ctx context.Context, arg SearchSessionDigestsParams) ([]SessionDigest, error)
	SetSessionChannel(ctx context.Context, arg SetSessionChannelParams) (Session, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateNotebookCompression(ctx context.Context, arg UpdateNotebookCompressionParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
	// Project-scoped command ledger: one row per normalized command,
	// shared across sessions. ok/fail counts merge additively so the row
	// is the running tally, not a per-session sample.
	UpsertCommandRun(ctx context.Context, arg UpsertCommandRunParams) error
	// One row per (normalized command, directory, error headline)
	// signature. A re-fail refreshes the observation -- headline, file
	// hints, and the observation's provenance all move with the latest
	// failure, not the first.
	UpsertFailure(ctx context.Context, arg UpsertFailureParams) error
	// The digest is a per-turn refresh of the session's resumable view:
	// title + latest checkpoint + touched files. ended_at follows the
	// session row's updated_at --- the closest thing to an end timestamp a
	// session has (sessions never formally end).
	UpsertSessionDigest(ctx context.Context, arg UpsertSessionDigestParams) error
}

var _ Querier = (*Queries)(nil)
