// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	BumpSessionCounter(ctx context.Context, arg BumpSessionCounterParams) error
	// Absolute user-turn ordinal source for edge_firings.turn_seq - the
	// bounded prompt-history query above can't serve it (DESC LIMIT 200
	// yields no ASC ordinal past 200 and same-second created_at ties are
	// ambiguous).
	CountUserMessagesBySession(ctx context.Context, sessionID string) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNotebookEntry(ctx context.Context, arg CreateNotebookEntryParams) (NotebookEntry, error)
	CreateNotebookTag(ctx context.Context, arg CreateNotebookTagParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteNotebookEntriesBySession(ctx context.Context, sessionID string) error
	DeleteProcessedSegmentsBySession(ctx context.Context, sessionID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetCollapsedTurnStats(ctx context.Context) (GetCollapsedTurnStatsRow, error)
	GetEdgeFiringStats(ctx context.Context) ([]GetEdgeFiringStatsRow, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastAssistantMessageBySession(ctx context.Context, sessionID string) (Message, error)
	GetLastSession(ctx context.Context) (Session, error)
	// Per-tool call count plus the number of distinct sessions that used
	// it: the per-session split the GROUP BY aggregate loses. Counts
	// attempted calls (tool-not-found results included), so flag-off
	// reach is measurable.
	GetMapUsage(ctx context.Context) (GetMapUsageRow, error)
	GetMaxNotebookEventNumber(ctx context.Context, arg GetMaxNotebookEventNumberParams) (int64, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetNotebookEntries(ctx context.Context, sessionID string) ([]NotebookEntry, error)
	GetNotebookEntriesByEventType(ctx context.Context, arg GetNotebookEntriesByEventTypeParams) ([]NotebookEntry, error)
	GetNotebookEntriesByTurn(ctx context.Context, arg GetNotebookEntriesByTurnParams) ([]NotebookEntry, error)
	GetNotebookEntriesByTurnSegment(ctx context.Context, arg GetNotebookEntriesByTurnSegmentParams) ([]NotebookEntry, error)
	GetNotebookEntryCount(ctx context.Context, sessionID string) (int64, error)
	GetNotebookTagsByEntry(ctx context.Context, entryID string) ([]string, error)
	GetNotebookTokenCount(ctx context.Context, sessionID string) (int64, error)
	GetNotebookTurnsWithEntries(ctx context.Context, arg GetNotebookTurnsWithEntriesParams) ([]int64, error)
	GetOldestNotebookEntries(ctx context.Context, arg GetOldestNotebookEntriesParams) ([]NotebookEntry, error)
	GetProcessedSegment(ctx context.Context, arg GetProcessedSegmentParams) (ProcessedSegment, error)
	// One row per tool result that renders as a stub (applied superseded
	// mark). content_head carries the first 1024 chars so callers can
	// recompute exact stub text for prefix-bearing stub kinds.
	GetPruningStats(ctx context.Context) ([]GetPruningStatsRow, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSessionCounter(ctx context.Context, arg GetSessionCounterParams) (int64, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	// One row per edge per run boundary; INSERT OR IGNORE makes the write
	// idempotent within a boundary, so callers count a firing only when
	// this reports a new row.
	InsertEdgeFiring(ctx context.Context, arg InsertEdgeFiringParams) (int64, error)
	// Backs prompt history when no session is open. Needs
	// idx_messages_role_created_at to seek rather than scan the table.
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// Messages from the summary onward, which is all a compacted session sends.
	// created_at has one-second resolution, so a few messages preceding the
	// summary can come back too; the caller slices from the summary by ID.
	ListMessagesBySessionFromSummary(ctx context.Context, arg ListMessagesBySessionFromSummaryParams) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListProcessedSegments(ctx context.Context, sessionID string) ([]ProcessedSegment, error)
	ListSessionCounters(ctx context.Context) ([]ListSessionCountersRow, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	// Backs prompt history, which steps back one entry at a time.
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	MarkSegmentProcessed(ctx context.Context, arg MarkSegmentProcessedParams) error
	// One row per collapsed prior turn; INSERT OR IGNORE makes the write
	// idempotent across renders and across processes sharing the session
	// DB, so callers count a turn only when this reports a new row.
	RecordCollapsedTurn(ctx context.Context, arg RecordCollapsedTurnParams) (int64, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RecordProcessedSegment(ctx context.Context, arg RecordProcessedSegmentParams) error
	RecordSegmentAttempt(ctx context.Context, arg RecordSegmentAttemptParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	SearchNotebookByTag(ctx context.Context, arg SearchNotebookByTagParams) ([]NotebookEntry, error)
	SearchNotebookByText(ctx context.Context, arg SearchNotebookByTextParams) ([]NotebookEntry, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateNotebookCompression(ctx context.Context, arg UpdateNotebookCompressionParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
}

var _ Querier = (*Queries)(nil)
